PREFIX besluitvorming: <http://data.vlaanderen.be/ns/besluitvorming#>

DELETE {
    GRAPH ?g {
       ?s besluitvorming:beschrijft ?o .
    }
}
INSERT {
    GRAPH ?g {
       ?s besluitvorming:genereertVerslag ?o .
    }
}
WHERE {
    GRAPH ?g {
       ?s besluitvorming:beschrijft ?o .
    }
}