PREFIX dct: <http://purl.org/dc/terms/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX besluitvorming: <http://data.vlaanderen.be/ns/besluitvorming#>

DELETE {
    GRAPH ?g {
        ?olderAgenda prov:wasRevisionOf ?newerAgenda .
    }  
}
INSERT {
  GRAPH ?g {
      ?newerAgenda prov:wasRevisionOf ?olderAgenda .
  }  
}
WHERE {
    GRAPH ?g {
        ?olderAgenda besluitvorming:isAgendaVoor ?vergadering .
        ?olderAgenda a besluitvorming:Agenda ;
            dct:title ?olderTitle ;
            dct:created ?olderCreated ;
            prov:wasRevisionOf ?newerAgenda .
        ?newerAgenda a besluitvorming:Agenda ;
            dct:title ?newerTitle ;
            dct:created ?newerCreated .
        FILTER ( DATATYPE(?olderCreated) = xsd:dateTime) # Avoid including results because of wrong datatype
        FILTER ( DATATYPE(?newerCreated) = xsd:dateTime) # Avoid including results because of wrong datatype
        FILTER (?newerCreated > ?olderCreated)
    }
}