modifications:
- change class of zitting
- add status to agenda as a code list, new class, TODO provide codelist
- change predicate connecting all agendas to vergaderactiviteit, but keeping behandelt as the one that defines the final one
- ext:aangemaaktOp -> dct:created
- added attachment relationship, currently not used
- ext:agendaNaam -> besluitvorming:volgnummer NOTE: property name reused with different meaning!!!!
- dct:title created with name of the agenda, set to agenda <volgnummer> van zitting op <datum>
- dct:type created, always set to besluitvorming:Agenda
- besluitvorming:heeftVorigeVersie -> prov:wasRevisionOf
- ext:getekendeNotule: moved from agenda to zitting, changed from file to document

voor agenda:
identificator: ?


