PREFIX pub: <http://mu.semte.ch/vocabularies/ext/publicatie/>

WITH <http://mu.semte.ch/graphs/organizations/kanselarij>
DELETE {
  ?numac ?p ?o
} WHERE {
  ?numac a pub:NumacNummer.
  ?numac ?p ?o .
}

WITH <http://mu.semte.ch/graphs/organizations/kanselarij>
DELETE {
  ?s2 pub:numacNummer ?numac
} WHERE {
  ?numac a pub:NumacNummer.
  ?s2 pub:numacNummer ?numac .
}