PREFIX dossier: <https://data.vlaanderen.be/ns/dossier#>
PREFIX besluitvorming: <http://data.vlaanderen.be/ns/besluitvorming#>
DELETE {
  GRAPH ?g {
    ?dossier ?p1 ?o1 .
    ?besluitvormingsaangelegenheid ?p2 ?o2 .
  }
}
WHERE {
  GRAPH ?g {
    VALUES (?dossier) {
     (<http://themis.vlaanderen.be/id/dossier/80a372d2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a357c0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a3383a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a316b6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a2de62-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a2fb90-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a2fc76-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a2ca30-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a2d32c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a2db2e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a29ec0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a2b5ae-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a22de6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a259ce-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a26cf2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a249e8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a1c40a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a23700-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a19c46-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a1e584-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a1f6a0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a15a56-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a1516e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a15c68-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a13ca6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a10a7e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a10efc-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a115be-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a10bd2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a0e102-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a09ecc-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a07de8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a08c8e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a07f32-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a06a56-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/809eee6a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/809eb4b8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/809d6e82-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/809d3232-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/809cd544-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/809b363a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/809b674a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/809b0aca-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/809a01b6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/809786b6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80976d70-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/809709b6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8096101a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8095c36c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8093a1a4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80939c86-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80937a9e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80932328-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/809325b2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80932486-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8091e3a0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80916dda-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/809067a0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/808fd25e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8090bd4a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/808f6274-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/808fcb06-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/808f05c2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80906ae8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/808f2bb0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/808f725a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/808f7156-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/808f6d32-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/808ebe8c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/808d3a9e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/808ecc56-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/808d3b7a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/808d2568-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/808cc686-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/808bfd0a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/808be7f2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/808bbe4e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/808bfbf2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8089bea0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80858cfe-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80858754-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80854a00-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80858092-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80851332-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8085617a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80851242-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8084e934-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/808446be-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8084dfd4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8082b308-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80825e3a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8082c244-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8082bbd2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80833db4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8081dc12-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8082893c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8082631c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8081d668-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8081e306-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80813582-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80815ae4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80811ef8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8081201a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807f96d2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8080fa90-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8080545a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80805c2a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8080caca-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8080831c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80808056-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/808025a2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807f594c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807f51c2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807f4948-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807ec216-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807e957a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807ea010-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807e3d28-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807e592a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807e2db0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807e5204-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807e56be-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807e2c7a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807e4aca-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807e1492-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807e11e0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807a2c60-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807cbaac-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807a2a8a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807a28c8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807bf3ba-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807c038c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807bd718-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8078d176-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80790ae2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8078e670-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80783ab8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8077f710-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807789ba-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8076c07a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/806db408-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/806d8bea-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/806e6b32-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/806d7646-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/806dcb8c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/806a392c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/806a34fe-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/806a4520-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8069d11c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8071d1c8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8071c8c2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/815abe56-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/815c1fd0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/809cde40-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/815bb270-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80bfe07a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80bfec64-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8157dace-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80bff1dc-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80de4074-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81962612-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80de422c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80bfeb74-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ad7624-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80de4402-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80bfe5f2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/818282e2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ee2836-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8163d8c4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8136e076-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8163f0b6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ee2926-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ee2674-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/814d1954-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ee2458-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a4c92a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8109927e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a4cae2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8187b8de-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f8626a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/814f05fc-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80d79d78-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807ea312-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a4c664-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a4cef2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a4c74a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807e9f34-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8174394e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807ea132-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/819e65a2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/819d06a8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/819e45b8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/819e3398-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/819c8f7a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/819d1026-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/819e47fc-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/819e58aa-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/819e3ec4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/819e5e22-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/819e3230-dec2-11e9-aa72-0242c0a80002>)
    }
      ?dossier dossier:Dossier.isNeerslagVan ?besluitvormingsaangelegenheid;
             ?p1 ?o1  .
      ?besluitvormingsaangelegenheid a besluitvorming:Besluitvormingsaangelegenheid;
                                   ?p2 ?o2  .
  }
}
