PREFIX dossier: <https://data.vlaanderen.be/ns/dossier#>
PREFIX besluitvorming: <http://data.vlaanderen.be/ns/besluitvorming#>
DELETE {
  GRAPH ?g {
    ?dossier ?p1 ?o1 .
    ?besluitvormingsaangelegenheid ?p2 ?o2 .
  }
}
WHERE {
  GRAPH ?g {
    VALUES (?dossier) {
     (<http://themis.vlaanderen.be/id/dossier/80fb33aa-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ef66c4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80fd352e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80faceba-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f12b1c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80facfc8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80fcc0c6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80d665fc-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f11e56-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f08c2a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80fb1988-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80fb7f90-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f0de0a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80fb2d88-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80faf746-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80fee6c6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f9fed6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f5eb16-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80fedc76-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f95bc0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f390a0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80fb21e4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f41548-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f83934-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f9ea72-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80fba0d8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80fb3774-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f5abb0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f3df6a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f773c8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f7e4ac-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f87796-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f8af7c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f9bef8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f9f756-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80fa61be-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f95238-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f58b9e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f26b3a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f83d44-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f73ff2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f7bf9a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f8d222-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f8dc36-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f57064-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f7edc6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f488d4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f9036e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f61bb8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f8ff22-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f98df2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f0087c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80fa78de-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f9efcc-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f98b36-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f7f0aa-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f81490-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ed1252-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f6e6a6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f62194-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f90788-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f6d67a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f81a6c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f8f608-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f071ea-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f155b0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f62aae-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f8f360-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f849c4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f64db8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f5b876-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f77508-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f62806-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f69fca-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f09ed6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f5d054-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f8cc0a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f8e118-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f51150-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f714d2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f74c68-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f7e1e6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f8115c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f58888-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f6ad76-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f68350-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f83484-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f5fc6e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f58342-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f93f28-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f107b8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f9510c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f6aaba-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f7e10a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f8f9aa-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ed80e8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f39776-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f1204a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f733ae-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f753fc-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80edd174-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f619a6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f6b4ba-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f73eee-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f7b0f4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f7a730-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e0da6e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e9a11c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80effdc8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f0057a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f4f2b0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f5174a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80dca9c6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f3732c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f0e9fe-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f08392-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f5246a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ea7e66-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f47d9e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f45ff8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f45f1c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f46214-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f463f4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f458aa-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f77b66-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f1ae5c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f1b03c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f1c5c2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f1cfc2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f3fb30-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f0870c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f0dffe-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f00296-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f09c1a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f2957e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f62964-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f53de2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f62284-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f140fc-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f2ff46-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f3efaa-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f55e08-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f553d6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f6c194-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f6c518-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f6c658-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80edc288-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f1be60-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f1e9f8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f4d5dc-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eeb602-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f24678-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e84f56-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f02244-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f12c02-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f23624-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80dd9296-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e29d0e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e1a07a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f61d8e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f5e3aa-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e1f368-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f4ed9c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f0f4ee-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f4cfba-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f1e28c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80efa260-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f03838-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f02320-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f057f0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f1dfa8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e64ef4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80edb64e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f3270a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f36cc4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f40616-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f48a82-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f498e2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ef94f0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f0078c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f3121a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e814dc-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ece3ae-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eda67c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e33cfa-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f4f594-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e85050-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f49d60-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e8d4d0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80efeb8a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f0a1c4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f0f8cc-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f4c506-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eadd84-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eea34c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f0ceba-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f33826-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ef7b78-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f05f84-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ebb0b0-dec2-11e9-aa72-0242c0a80002>)
    }
      ?dossier dossier:Dossier.isNeerslagVan ?besluitvormingsaangelegenheid;
             ?p1 ?o1  .
      ?besluitvormingsaangelegenheid a besluitvorming:Besluitvormingsaangelegenheid;
                                   ?p2 ?o2  .
  }
}
