PREFIX dossier: <https://data.vlaanderen.be/ns/dossier#>
PREFIX besluitvorming: <http://data.vlaanderen.be/ns/besluitvorming#>
INSERT {
  GRAPH ?g {
    ?besluitvormingsaangelegenheid dossier:doorloopt ?procedurestap .
  }
}
WHERE {
  GRAPH ?g {
    VALUES (?besluitvormingsaangelegenheid ?procedurestap) {
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50AD00-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f9e568-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50AD00-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f3c3cc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D512E06-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f95d00-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D512E06-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f01272-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50C575-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f9920c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50C575-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f3e0fa-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D527D61-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f97a1a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D527D61-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/598e39a8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53A672-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f98974-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53A672-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f80f18-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54C890-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f98b22-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54C890-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59de3188-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D548EE9-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f8bb8e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D548EE9-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e5ee50-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54F68A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f92556-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54F68A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f768ce-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D542426-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f8f3d8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D542426-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f49ea0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54DC68-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f8fb08-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54DC68-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f44464-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53317E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f91ae8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53317E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f086d0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51000D-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f82ff2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51000D-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f3d86c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D543FB0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f87a84-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D543FB0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f67540-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53CFBC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f88ec0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53CFBC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f3336c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53FED9-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f87566-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53FED9-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e68838-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D530DDE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f8374a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D530DDE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f3da06-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54AEF0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f82930-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54AEF0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e54c16-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5500DA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f7fcf8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5500DA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f515a6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54441A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f7b0d6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54441A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f39654-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50F60C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f785e8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50F60C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f0de32-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5490E6-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f7ec36-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5490E6-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f0adc2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54DFED-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f6d38c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54DFED-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f65510-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D555A3A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f71752-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D555A3A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f24e7a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D528D00-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f6f402-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D528D00-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f45008-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50DC6D-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f6fa9c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50DC6D-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f39d2a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51D824-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f74150-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51D824-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e968be-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D544B55-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f726d4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D544B55-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f45f3a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55EBE4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f724e0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55EBE4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e826e8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D511101-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f71e00-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D511101-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f0a566-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50CFA6-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f73c5a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50CFA6-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59779504-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5103B8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f62766-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5103B8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ef1872-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54DB00-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f6739c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54DB00-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f31878-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53DCDC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f5f46c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53DCDC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f31b98-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52C7D4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f5c17c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52C7D4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59eb1e48-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D546DFB-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f5ef6c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D546DFB-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e80c4e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51891E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f5ed78-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51891E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f2346c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D532DB5-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f59792-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D532DB5-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f30018-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55D32A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f53a68-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55D32A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ef5e90-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5630FE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f5a188-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5630FE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f4702e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50D29F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f54558-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50D29F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59efca92-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50A7BA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f533b0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50A7BA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ef5cec-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53C851-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f5190c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53C851-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ebc014-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53F1C3-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f5084a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53F1C3-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f2b6b2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53A4F7-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f4abde-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53A4F7-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f1101e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5338AE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f509f8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5338AE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ed029e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54D1F0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f4a4f4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54D1F0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ef1bd8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D541D5A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f4c0e2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D541D5A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59b61d4c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D539DE4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f50f02-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D539DE4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ef605c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D517E4D-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f43168-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D517E4D-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ef4748-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D512B68-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f44ae0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D512B68-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f21df6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51C5DC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f437f8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51C5DC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f0cbc2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D548723-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f42dda-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D548723-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f0ce42-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51E2CE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f445fe-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51E2CE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f04666-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54450A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f3f6ee-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54450A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59edbfb8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51EE0E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f41fde-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51EE0E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59efee96-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5367F2-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f3d6c8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5367F2-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59efc3c6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D526028-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f3d1dc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D526028-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f0af7a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D515804-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f3a432-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D515804-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ef28ee-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55EF36-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f3b5d0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55EF36-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ecc66c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5240A2-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f33650-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5240A2-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f0d1a8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54627F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f367f6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54627F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f0b5ce-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55FDBE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f36350-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55FDBE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ee8934-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D535A79-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f30392-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D535A79-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ef3726-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52CD10-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f30f4a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52CD10-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e89da8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53632F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f306ee-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53632F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f0c212-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D554DB0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f30dc4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D554DB0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f0f53e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D560FA2-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f284b2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D560FA2-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f1273e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52755F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f282d2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52755F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59eea84c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D511859-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f27616-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D511859-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ef77ea-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D549DFC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f2bc0c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D549DFC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ed0424-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51F8EA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f2ba86-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51F8EA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ec2a4a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54EB23-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f2bf0e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54EB23-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f1151e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D538034-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f27c60-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D538034-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ef7628-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54FAEA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f21cca-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54FAEA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f14534-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52501A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f25898-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52501A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59eea374-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5192E3-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f24114-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5192E3-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59eaed92-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D534CF5-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f2245e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D534CF5-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59eb79d8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D553A82-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f172fc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D553A82-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f0bc86-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52757C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f190de-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52757C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ef3bf4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52F6B5-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f1f22c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52F6B5-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ed9a06-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50C010-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f10ccc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50C010-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59eea6bc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D554811-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f130e4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D554811-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59eea1ee-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D536A7C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59efbd72-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D536A7C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e87f44-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55B7D2-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f111b8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55B7D2-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e99bd6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5547AC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f13a44-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5547AC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59eca1fa-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52DBCA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f0b290-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52DBCA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e1df90-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51BBFA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f138a0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51BBFA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59eca074-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51FD68-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f0d338-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51FD68-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ec6f00-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51E788-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f0a714-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51E788-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e5135e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51549E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f08860-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51549E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59eb3892-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D551872-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f07ed8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D551872-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e94000-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D515156-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f1013c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D515156-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59bedcd4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54E398-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f07d52-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54E398-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e93e48-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D514C4C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f0f1e2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D514C4C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e61e16-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8F8A959B-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59f0f368-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8F8A959B-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e8c35a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D559266-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ef2236-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D559266-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e8bdba-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D553348-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ef4d7e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D553348-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ec863e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D529D54-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ef3d70-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D529D54-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e83732-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D544D7A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ef4bee-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D544D7A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59edf456-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D556584-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59eec80e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D556584-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e71f28-dec1-11e9-aa72-0242c0a80002> )
    }
    ?procedurestap ?p ?o .
    FILTER NOT EXISTS { ?besluitvormingsaangelegenheid dossier:doorloopt ?procedurestap . }
  }
}