PREFIX dossier: <https://data.vlaanderen.be/ns/dossier#>
PREFIX besluitvorming: <http://data.vlaanderen.be/ns/besluitvorming#>
INSERT {
  GRAPH ?g {
    ?besluitvormingsaangelegenheid dossier:doorloopt ?procedurestap .
  }
}
WHERE {
  GRAPH ?g {
    VALUES (?besluitvormingsaangelegenheid ?procedurestap) {
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D520E99-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3f1998-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50EEC8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4ff5e2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50EEC8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b465db6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50EEC8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3cd502-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D559AAE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4fda3a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D559AAE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b48b264-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D559AAE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b42a5ea-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D541774-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4ff3d0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D541774-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b46585c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D541774-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3cd782-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D550A44-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4fe30e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D550A44-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b479104-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D550A44-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3faa98-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D550E37-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4fefde-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D550E37-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b491024-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D550E37-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3ee2a2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52556B-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4ff1c8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52556B-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b48dd7a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52556B-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4178a0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D519D1E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4f0cc2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D519D1E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b46d912-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D519D1E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b44d0ea-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D511499-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4f0484-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D511499-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4a5f7e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D511499-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3f6e02-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54C732-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4f1a78-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54C732-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3d243a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54C732-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b344b58-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D536BBC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4f2e50-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D536BBC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b466b94-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D536BBC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b44d9be-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54424F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4f0f2e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54424F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b46ecae-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54424F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3e3c62-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D552FC5-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4ef3d6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D552FC5-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4a1906-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D552FC5-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3f5912-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5334EE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4d83ac-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5334EE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4299ec-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5334EE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3ede4c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55554E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4d7cea-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55554E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b45abb4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55554E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3ef2b0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55B0D4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4c0392-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55B0D4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b45b712-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55B0D4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3fa142-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50AE86-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4c41e0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50AE86-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4160d6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50AE86-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3e4b9e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54CF8F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4bca58-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54CF8F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b45bdc0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54CF8F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b41adb6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D543CA4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4c3970-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D543CA4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b415a1e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D543CA4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3e5332-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D552F2F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4c60ee-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D552F2F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b44c244-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D552F2F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3ea0bc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D551B24-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b49b614-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D551B24-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4332b2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D551B24-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3ab8f8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5593BA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4a098e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5593BA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b433df2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5593BA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3ed122-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51D84C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4a1f96-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51D84C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b30855e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51D84C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b1c62d6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D531BF8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4a21f8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D531BF8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b42e5be-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D531BF8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3dc318-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53BC48-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4868f4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53BC48-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b42ed8e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53BC48-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b2d9916-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5312B7-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b48d00a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5312B7-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b43af80-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5312B7-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b37378c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52A010-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b490746-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52A010-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b46fea6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52A010-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b44df04-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D549FC9-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b48af26-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D549FC9-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b43cb64-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D549FC9-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3f00b6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D541EEA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b47a73e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D541EEA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b43e324-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D541EEA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3d2d0e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5216CC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4773ea-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5216CC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b42faea-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5216CC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3caa78-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53A4E2-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b479abe-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53A4E2-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b432cfe-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53A4E2-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3f7794-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D535960-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4796f4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D535960-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4329d4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D535960-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3eefcc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D560823-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b474de8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D560823-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b40df94-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D560823-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3f0fa2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52BA1E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4616e4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52BA1E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3ef9e0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52BA1E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b37aa28-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54B6AC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b46253a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54B6AC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b421fe4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54B6AC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3cc24c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5567E6-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b45c2fc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5567E6-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b41aba4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5567E6-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3bb51e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55725E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b45add0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55725E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3efe4a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55725E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b37a2e4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53DB24-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b457fa4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53DB24-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b42357e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53DB24-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b409278-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54FD4C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b45c022-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54FD4C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b41afdc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54FD4C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3f6268-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53BB12-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b4592fa-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53BB12-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3cdc50-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53BB12-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b33e0d2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D548A88-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b44bb14-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D548A88-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3cbd2e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D548A88-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b387f2a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5416D4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b43bed0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5416D4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b40faba-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5416D4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3b8c38-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54A19E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b431ba6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54A19E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b353a9a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54A19E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b23936c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5311F8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b433802-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5311F8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3d3466-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5311F8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b36641a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55FA6C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b42b2f6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55FA6C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b36327e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55FA6C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b28b0fe-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D56382E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b421b5c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D56382E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3efc42-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D56382E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b386936-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D552DB3-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b421daa-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D552DB3-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3bcde2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D552DB3-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b355732-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51E6AD-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b41118a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51E6AD-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b39701a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51E6AD-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3488c0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52D8E6-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b40575e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52D8E6-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3f9bde-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52D8E6-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b2c4c8c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51C69A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b40829c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51C69A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b39ea72-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51C69A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b371eaa-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54D327-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b408512-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54D327-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b0238ac-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54D327-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5af86304-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D542A5D-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3ec736-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D542A5D-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b38a81a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D542A5D-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3541de-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53A3CA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3de0aa-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53A3CA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3859be-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53A3CA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3483fc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D534BBE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3e6c46-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D534BBE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b38b65c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D534BBE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b346f20-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5518D6-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3f0d18-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5518D6-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b37b248-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5518D6-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3292ae-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D534B65-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3d068a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D534B65-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b351c18-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D534B65-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b255f26-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53E8C6-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3d3aa6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53E8C6-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3ad4aa-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53E8C6-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b375546-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5237A7-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3d1738-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5237A7-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b37ec0e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5237A7-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3295b0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54EC4E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3b1fdc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54EC4E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b36afec-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54EC4E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3288a4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D530E56-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b39bd68-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D530E56-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3506b0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D530E56-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b23b964-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D561C36-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b396be2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D561C36-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b356326-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D561C36-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b2fd94c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50AB3E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b38730e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50AB3E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b334ff0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50AB3E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b23b720-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D540997-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b3870a2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D540997-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b33ba44-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D540997-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b2e3970-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D544424-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b38a306-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D544424-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b326d92-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D544424-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b2afc42-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54CB24-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b379c0e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54CB24-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b33bc56-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54CB24-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b2f5a44-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55FAD1-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b37c4c2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55FAD1-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b337dfe-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55FAD1-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b2f9a72-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51B33B-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b37e25e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51B33B-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b336864-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51B33B-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b2dfcd0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5231FC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5b373a20-dec1-11e9-aa72-0242c0a80002> )
    }
    ?procedurestap ?p ?o .
    FILTER NOT EXISTS { ?besluitvormingsaangelegenheid dossier:doorloopt ?procedurestap . }
  }
}