PREFIX dossier: <https://data.vlaanderen.be/ns/dossier#>
PREFIX besluitvorming: <http://data.vlaanderen.be/ns/besluitvorming#>
INSERT {
  GRAPH ?g {
    ?besluitvormingsaangelegenheid dossier:doorloopt ?procedurestap .
  }
}
WHERE {
  GRAPH ?g {
    VALUES (?besluitvormingsaangelegenheid ?procedurestap) {
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52FB00-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/594b401c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52FB00-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5949bc88-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55286C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/594afecc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55286C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5936e11c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55CBB4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/594a9a5e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55CBB4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59497bb0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55FDC9-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/594a8c3a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55FDC9-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593ee326-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54D628-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/594a7ac4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54D628-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59452bbe-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52DDFA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/594a7420-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52DDFA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593cb8d0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52C374-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/594a33f2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52C374-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593ca098-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5245CB-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/594a1192-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5245CB-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5936873a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50DA79-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/594a4824-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50DA79-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59454d38-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D561F24-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5949e3d4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D561F24-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5948e11e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5390E2-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5949b5d0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5390E2-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593a04fa-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52EE12-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5949d0ec-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52EE12-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593d85b2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55D029-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5949d650-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55D029-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5912130a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51B8D0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/594804d8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51B8D0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59468e00-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55FA3B-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59485f82-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55FA3B-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5942b9e2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53105E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59486f0e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53105E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5944a0c2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52E8EA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/594870b2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52E8EA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59393bb0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5462EC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5948758a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5462EC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5943f7e4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51B449-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59485dca-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51B449-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5945d01e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5648C8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59486310-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5648C8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5945c3d0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55706A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5947241e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55706A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593ec06c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54F39C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5947a1e6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54F39C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59462e7e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D562F8C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59470ad8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D562F8C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5944df10-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D547EEE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59477400-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D547EEE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59121512-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8F8A6EE5-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59467e4c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8F8A6EE5-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5945d884-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D513FA4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5946bad8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D513FA4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59462230-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51A44F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5946c15e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51A44F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/594212d0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D525448-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5946c852-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D525448-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59410318-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8F8A7772-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59460138-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8F8A7772-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59454252-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D553244-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59463018-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D553244-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5944f6bc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D548381-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5945ff1c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D548381-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5943b6f8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51B95D-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59461d62-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51B95D-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593c3ef0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51D771-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5944ec62-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51D771-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593bad64-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D530BAF-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59449b7c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D530BAF-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59444b7c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D561A74-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5944390c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D561A74-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5933e78c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D513091-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59442b92-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D513091-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593d8af8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52653C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/594423ea-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52653C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593ee6a0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55A17A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59444802-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55A17A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59321af6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D517A64-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59436d9c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D517A64-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5938a89e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52552E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59438ffc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52552E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593a8fc4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D558118-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/594329f4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D558118-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5942bda2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5566EC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/594303de-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5566EC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59422284-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8F8A3F1E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5942a808-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8F8A3F1E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59428012-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51A2AB-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5942bf8c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51A2AB-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5941f336-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D545B09-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59426cbc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D545B09-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5936eb9e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55C165-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59424b06-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55C165-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593a820e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D515C00-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59426622-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D515C00-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5936f2c4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53E467-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5942589e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53E467-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5936f0f8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D522CA2-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5942516e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D522CA2-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593c9b48-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D536036-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59424e44-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D536036-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5932be70-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50D03C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59422a90-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50D03C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5941c578-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50B732-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59420c7c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50B732-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593d7694-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55676F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/594119fc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55676F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593f02de-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53B285-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59414e40-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53B285-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593d83fa-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53A2B2-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59414558-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53A2B2-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59379db4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50E18A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59411b28-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50E18A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593c8338-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5432E0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/594175dc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5432E0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593edc3c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D522447-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59413e82-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D522447-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5938aa38-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52B119-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5941778a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52B119-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593ea83e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D513A68-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5940d6b8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D513A68-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593f082e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55B642-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5940e89c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55B642-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/594039ba-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D524610-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5940e220-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D524610-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/594017f0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D559ACD-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59409f7c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D559ACD-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593eb540-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54B17B-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5940e3c4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54B17B-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59401b24-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D536252-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5940ba02-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D536252-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59361958-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55BA2B-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5940bd72-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55BA2B-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593a8df8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51BB0B-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5940dd3e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51BB0B-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593eff6e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53F550-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5940acc4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53F550-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593c93f0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D550800-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/594019c6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D550800-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593d5b28-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53FB4A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/594016c4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53FB4A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593f591e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D510E31-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59402b32-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D510E31-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593d8cc4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D516B28-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59403884-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D516B28-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593d5ec0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54FF2D-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5940409a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54FF2D-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593ec936-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D560818-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593fb0c6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D560818-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593f7034-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D553777-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593fc41c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D553777-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593b0184-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53F172-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593fc282-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53F172-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593d9ca0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8F8A74E8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593fc73c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8F8A74E8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593ec79c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55A968-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593fc5ac-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55A968-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593f7714-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8F8A93C4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593fca7a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8F8A93C4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593f36be-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52C716-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593fc8cc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52C716-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593f895c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5296EC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593fb206-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5296EC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593c99a4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5461AC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593e2f76-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5461AC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593d5222-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D546832-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593e00d2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D546832-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/58fb1d1c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54C2D2-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593eaa46-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54C2D2-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593d6bea-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D530CE5-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593f1314-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D530CE5-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59176012-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54C89A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593f249e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54C89A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593babca-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55C5EC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593f78ea-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55C5EC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5939d00c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5118A8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593f6e86-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5118A8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/58e25c8c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D536D1A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593ebb76-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D536D1A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593aa450-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D520D6C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593f4d0c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D520D6C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5934ff00-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5443A3-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593d281a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5443A3-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593c5746-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52BABF-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593d194c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52BABF-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59397b0c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D525A92-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593d8eae-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D525A92-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5937bf56-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D536090-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593d7338-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D536090-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5939b644-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51CB55-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593d6f3c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51CB55-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5939b2e8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D554C20-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593d65fa-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D554C20-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59334d36-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53100E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593d70e0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53100E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5939b482-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D531D24-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593c485a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D531D24-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593bcb82-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50E28E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593c2802-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50E28E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593b180e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8F8A23C6-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593c7adc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8F8A23C6-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/593baa12-dec1-11e9-aa72-0242c0a80002> )
    }
    ?procedurestap ?p ?o .
    FILTER NOT EXISTS { ?besluitvormingsaangelegenheid dossier:doorloopt ?procedurestap . }
  }
}