PREFIX dossier: <https://data.vlaanderen.be/ns/dossier#>
PREFIX besluitvorming: <http://data.vlaanderen.be/ns/besluitvorming#>
PREFIX dct: <http://purl.org/dc/terms/>
INSERT {
  GRAPH ?g {
    ?dossier a dossier:Dossier .
    ?dossier dossier:Dossier.isNeerslagVan ?besluitvormingsaangelegenheid .
    ?besluitvormingsaangelegenheid a besluitvorming:Besluitvormingsaangelegenheid .
    ?besluitvormingsaangelegenheid dossier:doorloopt ?procedurestap .
  }
}
WHERE {
  GRAPH ?g {
    VALUES (?dossier ?besluitvormingsaangelegenheid ?procedurestap) {
      ( <http://themis.vlaanderen.be/id/dossier/dbc331ca-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc331cb-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5945329e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52d80-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52d81-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/594215dc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52d80-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52d81-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/593f84ca-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52d82-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52d83-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/593bf1ac-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52d82-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52d83-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/593500c2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52d84-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52d85-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/593c08ae-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52d84-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52d85-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5935bd0a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52d86-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52d87-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5938c9fa-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52d86-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52d87-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59310648-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52d88-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52d89-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/593886e8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52d88-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52d89-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5937938c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52d8a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52d8b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5934fd48-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52d8a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52d8b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5918d258-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52d8c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52d8d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/593325e0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52d8c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52d8d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5919c10e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52d8e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52d8f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5932857c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52d8e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52d8f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59310512-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52d90-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52d91-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/591c1968-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52d90-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52d91-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58cd211e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52d92-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52d93-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5917e3e8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52d92-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52d93-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58dd6a42-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52d94-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52d95-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59163bc4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52d94-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52d95-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59155844-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52d96-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52d97-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5913ad3c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52d96-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52d97-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/590c6720-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52d98-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52d99-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/590faa5c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52d98-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52d99-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59066820-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52d9a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52d9b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/590fb826-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52d9a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52d9b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/590a9ee0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52d9c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52d9d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/590fe7a6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52d9c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52d9d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/590cacb2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52d9e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52d9f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/590fedbe-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52d9e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52d9f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5909c326-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52da0-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52da1-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/590ecf92-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52da0-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52da1-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/590a917a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52da2-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52da3-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/590d8dda-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52da2-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52da3-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5907d7a0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52da4-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52da5-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/590d5bc6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52da4-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52da5-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58f14832-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52da6-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52da7-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59034726-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52da6-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52da7-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5900ef6c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52da8-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52da9-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58f06160-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52da8-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52da9-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58f009e0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52daa-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dab-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58efbf08-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52daa-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dab-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58ef8eca-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dac-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dad-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58eec080-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dac-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dad-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58ee3552-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dae-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52daf-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58ee580c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dae-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52daf-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58ee3872-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52db0-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52db1-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58ed8cec-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52db0-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52db1-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58ed1a50-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52db2-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52db3-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58ecd202-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52db2-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52db3-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58ec7c6c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52db4-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52db5-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58ec7dd4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52db4-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52db5-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58ec410c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52db6-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52db7-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58ea0ab8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52db6-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52db7-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e9ba0e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52db8-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52db9-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e9ca44-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52db8-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52db9-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e9852a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dba-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dbb-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e98f70-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dba-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dbb-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e54848-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dbc-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dbd-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e86ef6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dbc-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dbd-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e7e1fc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dbe-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dbf-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e88558-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dbe-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dbf-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e845fc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dc0-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dc1-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e7aeb2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dc0-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dc1-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e74f44-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dc2-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dc3-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e7ecce-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dc2-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dc3-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e2212c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dc4-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dc5-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e74bc0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dc4-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dc5-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e5db6e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dc6-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dc7-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e5f8ec-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dc6-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dc7-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e3d6ca-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dc8-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dc9-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e5b6e8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dc8-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dc9-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e5ab3a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dca-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dcb-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e54212-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dca-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dcb-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e4f028-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dcc-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dcd-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e55306-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dcc-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dcd-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e4995c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dce-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dcf-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e543a2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dce-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dcf-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e4f230-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dd0-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dd1-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e54e7e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dd0-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dd1-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e26c4a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dd2-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dd3-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e16688-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dd2-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dd3-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e0dbc8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dd4-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dd5-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e1314a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dd4-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dd5-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e10d50-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dd6-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dd7-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e03d08-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dd6-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dd7-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58dffe38-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dd8-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dd9-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e03b64-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dd8-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52dd9-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58dffb22-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dda-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52ddb-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58e00414-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dda-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52ddb-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58df4614-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52ddc-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52ddd-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58dfdcdc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52ddc-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52ddd-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58dfd05c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dde-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52ddf-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58df3cc8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52dde-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52ddf-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58df07d0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52de0-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52de1-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58df3b38-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc52de0-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc52de1-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58df064a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc55490-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc55491-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58df0c44-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc55490-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc55491-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58ded8dc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc55492-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc55493-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58df0f6e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc55492-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc55493-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58debdb6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc55494-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc55495-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58defcc2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc55494-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc55495-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58decdc4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc55496-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc55497-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58df1108-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc55496-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc55497-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58dee610-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc55498-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc55499-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58df0abe-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc55498-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc55499-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58debaaa-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc5549a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc5549b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58dee1ba-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc5549a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc5549b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58dea0a6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc5549c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc5549d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58de97b4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc5549c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc5549d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58de55ba-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc5549e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc5549f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58de4228-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc5549e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc5549f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58de1c6c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554a0-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554a1-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58ddbda8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554a0-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554a1-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58dda048-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554a2-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554a3-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58dd3d24-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554a2-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554a3-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58dc94b4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554a4-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554a5-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58dca684-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554a4-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554a5-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58dc617e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554a6-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554a7-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58dc85dc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554a6-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554a7-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58dc4b08-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554a8-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554a9-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58dc03dc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554a8-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554a9-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58dbdf24-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554aa-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554ab-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58db91c2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554aa-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554ab-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58db525c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554ac-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554ad-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58db631e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554ac-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554ad-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58db29a8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554ae-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554af-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58db269c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554ae-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554af-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58cb43a8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554b0-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554b1-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58dae5f6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554b0-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554b1-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58dab3ec-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554b2-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554b3-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58dae8ee-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554b2-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554b3-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58dac49a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554b4-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554b5-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58da83ae-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554b4-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554b5-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58da4fce-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554b6-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554b7-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58d90952-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554b6-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554b7-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58d228ee-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554b8-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554b9-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58d7fb52-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554b8-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554b9-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58d76778-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554ba-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554bb-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58d7d37a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554ba-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554bb-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58d37a96-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554bc-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554bd-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58d7b4da-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554bc-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554bd-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58d70ee0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554be-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554bf-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58d71b74-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554be-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554bf-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58cca162-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554c0-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554c1-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58d6e8b6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554c0-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554c1-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58d5eef2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554c2-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554c3-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58d6bfd0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554c2-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554c3-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58d67c28-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554c4-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554c5-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58d6baf8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554c4-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554c5-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58d2970c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554c6-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554c7-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58d66bc0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554c6-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554c7-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58d62660-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554c8-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554c9-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58d5da8e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554c8-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554c9-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/58d569be-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554ca-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554cb-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b61faee-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554cc-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554cd-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b611a20-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554ce-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554cf-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b61e680-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554d0-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554d1-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b620a02-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554d2-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554d3-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b623022-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554d4-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554d5-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b6207f0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554d6-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554d7-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b620dd6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554d8-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554d9-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b620ffc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554da-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554db-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b622640-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554dc-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554dd-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b61ece8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554de-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554df-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b621844-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554e0-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554e1-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b61f2d8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554e2-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554e3-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b61eef0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554e4-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554e5-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b622262-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554e6-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554e7-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b61f4cc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554e8-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554e9-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b61e414-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554ea-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554eb-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b611944-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554ec-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554ed-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b5f585c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554ee-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554ef-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b601b16-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554f0-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554f1-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b600afe-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554f2-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554f3-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b6027b4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554f4-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554f5-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b602174-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554f6-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554f7-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b60384e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554f8-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554f9-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b605626-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554fa-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554fb-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b603db2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554fc-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554fd-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b602552-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc554fe-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc554ff-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b601184-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc55500-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc55501-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b601738-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc55502-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc55503-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b605d60-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc55504-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc55505-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b5f8cbe-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc55506-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc55507-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b602980-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc55508-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc55509-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b600d56-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc5550a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc5550b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b600fa4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc5550c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc5550d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b6030a6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc5550e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc5550f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b606f1c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc55510-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc55511-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b60769c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc55512-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc55513-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b606710-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc55514-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc55515-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b604cb2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc55516-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc55517-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b604a82-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc55518-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc55519-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b5ebd8e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc5551a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc5551b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b5ebffa-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc5551c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc5551d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b5ec996-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbc5551e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbc5551f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5b5ec27a-dec1-11e9-aa72-0242c0a80002> )
    }
    ?procedurestap ?p ?o .
  }
}