PREFIX dossier: <https://data.vlaanderen.be/ns/dossier#>
PREFIX besluitvorming: <http://data.vlaanderen.be/ns/besluitvorming#>
INSERT {
  GRAPH ?g {
    ?besluitvormingsaangelegenheid dossier:doorloopt ?procedurestap .
  }
}
WHERE {
  GRAPH ?g {
    VALUES (?besluitvormingsaangelegenheid ?procedurestap) {
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D555E40-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e7121c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51B4D4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ecccd4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51B4D4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ea81e0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51B4D4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59dab530-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5546EE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ece246-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5546EE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ea90a4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5546EE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e821ac-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53442A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ecd922-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53442A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e80f5a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53442A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e1da22-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55C664-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ec70b8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55C664-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e7a8a8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55C664-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e5105c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53FB86-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ec725c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53FB86-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e7ad6c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53FB86-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e5088c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50D0DD-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59eb4d28-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50D0DD-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e78b98-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50D0DD-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59db5512-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53099D-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59eadb90-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53099D-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e6381a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53099D-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e2af74-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5608C2-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ea03dc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5608C2-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e992bc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5608C2-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e3e7f4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5294A9-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ea13ae-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5294A9-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e59f40-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5294A9-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e20506-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D532030-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e98baa-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D532030-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e6f890-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D532030-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e3d912-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51E6C0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e93c9a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51E6C0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59de3958-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51E6C0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59893dea-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D522249-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e929d0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D522249-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e4aed2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D522249-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d58b96-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52A04C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e920ca-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52A04C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e33bb0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52A04C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59de7f80-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52AB1F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e8c238-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52AB1F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e84754-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52AB1F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59dee4d4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5599DC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e6e4ae-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5599DC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59cfd020-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5599DC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59c47270-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5435BA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e7d422-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5435BA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e368d8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5435BA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d10076-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5379EA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e7d74c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5379EA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e3675c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5379EA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d0fedc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D544231-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e7abc8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D544231-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e1a066-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D544231-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59de9236-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D552236-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e74fb6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D552236-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e24a66-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D552236-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59dfc70a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5450AE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e7d5a8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5450AE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e36afe-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5450AE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d1021a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8F8A16F6-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e7d8e6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8F8A16F6-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e36c98-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8F8A16F6-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d17d6c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50BB07-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e68fe0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50BB07-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e1d3b0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50BB07-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e03078-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5309B0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e56e8a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5309B0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e4fa18-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5309B0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e05058-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55B660-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e5b84a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55B660-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d89ca0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55B660-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59ce4ebc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52455C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e5c16e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52455C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e08d84-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52455C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d02e80-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53F6EA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e5bfe8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53F6EA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e12032-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53F6EA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59dc9576-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D562D16-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e5be4e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D562D16-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59db8f50-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D562D16-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d4bedc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5273D8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e5bcc8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5273D8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59db8848-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5273D8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d4bae0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5587BD-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e5bb4c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5587BD-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d88e5e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5587BD-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59c9e23c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51C1C2-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e5ad46-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51C1C2-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d7070a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51C1C2-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d292c4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D56058F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e4f298-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D56058F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e47444-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D56058F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59de362e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53D8A4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e46a6c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53D8A4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e15084-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53D8A4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59dee146-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52C43D-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e41b02-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52C43D-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59df7a16-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52C43D-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59dc6c90-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50A7D8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e38a2a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50A7D8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e0a968-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50A7D8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e067b4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50A788-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e27b76-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50A788-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59da5252-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50A788-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d2e3b4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51889C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e2298c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51889C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59dcabd8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51889C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d973a0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D557719-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e23008-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D557719-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59db36d6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D557719-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d70ba6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D561A56-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e1ca32-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D561A56-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59deaafa-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D561A56-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59cc78d0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D528350-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e1c3e8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D528350-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59dea78a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D528350-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59cc772c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54596F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e1bd6c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54596F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59dea456-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54596F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59cc7592-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8F8A72D6-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e1cd2a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8F8A72D6-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59deb180-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8F8A72D6-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59c4d4cc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D519F8A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e14f08-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D519F8A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d9eb78-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D519F8A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d2dcac-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53BB59-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e08064-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53BB59-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59bf817a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53BB59-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59b720f2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54C7F0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e0c84e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54C7F0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d9df16-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54C7F0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d644aa-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54778C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59e065f2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54778C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d9e646-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54778C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59cfc62a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50A379-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59df7eda-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50A379-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d919f0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50A379-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d68cd0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D528940-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59df8060-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D528940-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d91d6a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D528940-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d65954-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53578A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59de948e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53578A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59db48a6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53578A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d7505c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53979A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59de8bec-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53979A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59da84de-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53979A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d28b94-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D556016-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59de858e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D556016-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59da8bdc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D556016-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d4f41a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D526582-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59defbcc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D526582-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d7433c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D526582-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59bfb15e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55495A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59de2c2e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55495A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d7480a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55495A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d1cbfa-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52B2A8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59dde52a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52B2A8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59cd20dc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52B2A8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59c5d322-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5361F8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59dd4976-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5361F8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d9889a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5361F8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d791a2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50AFC7-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59dd4fe8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50AFC7-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d9966e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50AFC7-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d4ec9a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52F826-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59dda7c2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52F826-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d76be6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52F826-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59cdc4a6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5188D8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59dd561e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5188D8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d99d4e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5188D8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d61a98-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51219A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59dcc9d8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51219A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d98f8e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51219A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d592bc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52D652-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59dc9ef4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52D652-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d8bfb4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52D652-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d58470-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51A322-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59dd089e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51A322-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d39174-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51A322-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59cebf96-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D553910-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59dc134e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D553910-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d9d2be-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D553910-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59c7b28c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D540D24-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59dc198e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D540D24-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d9d98a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D540D24-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59c7b98a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D540717-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59dc6b14-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D540717-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d67560-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D540717-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59cf580c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52BB22-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59dbffb2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52BB22-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d534c0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52BB22-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d3caae-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8F8A57C4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59dc0d04-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8F8A57C4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d9cba2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8F8A57C4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59c7ab70-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D549ECF-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59daf536-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D549ECF-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d8ecb4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D549ECF-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59d43926-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D520237-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/59dad01a-dec1-11e9-aa72-0242c0a80002> )
    }
    ?procedurestap ?p ?o .
    FILTER NOT EXISTS { ?besluitvormingsaangelegenheid dossier:doorloopt ?procedurestap . }
  }
}