PREFIX dossier: <https://data.vlaanderen.be/ns/dossier#>
PREFIX besluitvorming: <http://data.vlaanderen.be/ns/besluitvorming#>
PREFIX dct: <http://purl.org/dc/terms/>
INSERT {
  GRAPH ?g {
    ?dossier a dossier:Dossier .
    ?dossier dossier:Dossier.isNeerslagVan ?besluitvormingsaangelegenheid .
    ?besluitvormingsaangelegenheid a besluitvorming:Besluitvormingsaangelegenheid .
    ?besluitvormingsaangelegenheid dossier:doorloopt ?procedurestap .
  }
}
WHERE {
  GRAPH ?g {
    VALUES (?dossier ?besluitvormingsaangelegenheid ?procedurestap) {
      ( <http://themis.vlaanderen.be/id/dossier/dbb946b3-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbb946b4-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a7a7b9c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbb946b3-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbb946b4-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a7a7da4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd40-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd41-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a7c7212-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd40-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd41-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a73db84-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd40-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd41-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a7274ce-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd42-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd43-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a7b2862-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd42-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd43-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a7691bc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd42-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd43-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a768fa0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd44-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd45-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a74a2ee-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd44-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd45-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a71812c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd44-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd45-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a709ec4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd46-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd47-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a71ee8c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd46-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd47-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a6b197c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd46-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd47-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a6a6b12-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd48-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd49-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a6fd700-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd48-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd49-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a6b2610-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd48-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd49-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a6b1b84-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd4a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd4b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a6f505a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd4a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd4b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a6b0a86-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd4a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd4b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a6a076c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd4c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd4d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a6cc6c8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd4c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd4d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a545a5c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd4c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd4d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a53ceb6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd4e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd4f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a6b27f0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd4e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd4f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a65a64a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd4e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd4f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a653732-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd50-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd51-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a668bb4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd50-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd51-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a656004-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd50-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd51-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a656a22-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd52-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd53-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a618b14-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd52-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd53-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a5e00fc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd52-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd53-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a5d734e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd54-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd55-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a5a33fa-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd54-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd55-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a593e82-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd54-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd55-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a593054-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd56-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd57-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a52586a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd56-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd57-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a42dcc8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd56-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd57-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a367bae-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd58-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd59-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a524032-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd58-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd59-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a38af32-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd58-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd59-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a382efe-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd5a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd5b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a4a7758-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd5a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd5b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a46f22c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd5a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd5b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a458e8c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd5c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd5d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a4767b6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd5c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd5d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a3ea09a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd5c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd5d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a3d94de-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd5e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd5f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a4477ae-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd5e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd5f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a404d82-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd5e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd5f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a3f9dd8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd60-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd61-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a4389fc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd60-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd61-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a4021b8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd60-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd61-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a3f43f6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd62-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd63-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a390c0c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd62-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd63-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a2c38ce-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd62-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd63-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a2b8c3a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd64-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd65-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a30bee4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd64-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd65-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a29f708-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd64-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd65-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a29b1e4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd66-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd67-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a3033ca-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd66-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd67-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a2c3fe0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd66-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd67-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a2b9a18-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd68-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd69-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a2b2a2e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd68-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd69-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a067490-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd68-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd69-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59d8475a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd6a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd6b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a230b0a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd6a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd6b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a12f332-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd6a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd6b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a12cec0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd6c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd6d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a224ee0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd6c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd6d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a1cd50a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd6c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd6d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a1c35f0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd6e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd6f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a203132-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd6e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd6f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a1e2d56-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd6e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd6f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a1d00de-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd70-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd71-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a1da7d2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd70-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd71-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a18c79e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd70-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd71-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a185d5e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd72-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd73-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a1e9d2c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd72-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd73-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59ff1222-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd72-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd73-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59e4145e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd74-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd75-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a1d34c8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd74-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd75-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a180ae8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd74-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbacd75-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a178ffa-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd76-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbaf450-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a17b048-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd76-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbaf450-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a1348b4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbacd76-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbaf450-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a126138-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbaf451-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbaf452-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a157e04-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbaf451-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbaf452-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a0d111a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbaf451-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbaf452-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a0c92bc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbaf453-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbaf454-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a101bda-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbaf453-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbaf454-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a04d176-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbaf453-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbaf454-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a04343c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbaf455-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbaf456-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a1022f6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbaf455-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbaf456-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a0c66e8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbaf455-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbaf456-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a0bcb70-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbaf457-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbaf458-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a102148-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbaf457-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbaf458-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a0c6558-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbaf457-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbaf458-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a0bc9e0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbaf459-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbaf45a-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a0e107e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbaf459-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbaf45a-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a0b344e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbaf459-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbaf45a-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a0a9bec-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb6980-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb6981-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a0a2acc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb6980-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb6981-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a082dc6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb6980-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb6981-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a07cff2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb6982-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb6983-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a09760e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb6982-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb6983-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a077a02-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb6982-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb6983-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a074cf8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb6984-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb6985-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a08aef4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb6984-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb6985-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a0258ba-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb6984-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb6985-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a01f302-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb6986-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb6987-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a0795fa-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb6986-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb6987-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59d52840-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb6986-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb6987-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59d46284-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb6988-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb6989-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a06fe4c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb6988-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb6989-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a013b88-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb6988-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb6989-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a0095ac-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb698a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb698b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a073ce0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb698a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb698b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a0341e4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb698a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb698b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a030472-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb698c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb698d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a05d63e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb698c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb698d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a048540-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb698c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb698d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a04652e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb698e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb698f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a04717c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb698e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb698f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a021eb8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb698e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb698f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a01be82-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb6990-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb6991-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a03b8f4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb6990-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb6991-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59ff9418-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb6990-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb6991-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59fe85b4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb6992-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb6993-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a0215d0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb6992-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb6993-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59ffde00-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb6992-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb6993-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59fe5bca-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb6994-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb6995-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a00367a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb6994-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb6995-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59ef257e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb6994-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb6995-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59ee6f9e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb6996-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb6997-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a00aaa6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb6996-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb6997-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59fbad12-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb6996-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb6997-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59fb7e96-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb6998-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb6999-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59fcaf6e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb6998-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb6999-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59c10a68-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb6998-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb6999-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59c0b752-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb699a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb699b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59f98cda-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb699a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb699b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59f8a0ea-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb699a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb699b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59f74966-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb699c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb699d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59f72d82-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb699c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb699d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59db7218-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb699c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb699d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59db112e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb699e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb699f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59f62086-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb699e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb699f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59ec5a4c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb699e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb699f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59ec2c02-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb69a0-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb69a1-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59f4c7c2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb69a0-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb69a1-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59ec741e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb69a0-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb69a1-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59ebf5de-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb69a2-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb69a3-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59f3fd92-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb69a2-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb69a3-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59f0fd86-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb69a2-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb69a3-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59e6eb3e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb69a4-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb69a5-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59f3bca6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb69a4-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb69a5-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59e94654-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb69a4-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb69a5-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59e7fa38-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb69a6-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb69a7-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59f381a0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb69a6-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb69a7-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59ecb910-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb69a6-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb69a7-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59ec5380-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb69a8-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb69a9-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59f3e2c6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb69a8-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb69a9-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59e88a02-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb69a8-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb69a9-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59e30442-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb9090-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb9091-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59f08a22-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb9090-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb9091-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59e36fea-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb9090-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb9091-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59e2f484-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb9092-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb9093-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59ed152c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb9092-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb9093-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59ea23f8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb9092-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb9093-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59e9d0ec-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb9094-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb9095-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59ebbe5c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb9094-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb9095-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59b71ef4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb9094-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb9095-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59b60226-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb9096-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb9097-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59e92e4e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb9096-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb9097-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59e5218c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb9096-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb9097-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59e511d8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb9098-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb9099-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59e93772-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb9098-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb9099-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59e7b122-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb9098-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb9099-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59e67c44-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb909a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb909b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59e815cc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb909a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb909b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59e2dbb6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb909a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb909b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/599cc5ae-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb909c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb909d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59e5a0e4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb909c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb909d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59e50ed6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb909c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb909d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59e15dc2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb909e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb909f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59e5c63c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb909e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb909f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59e1e86e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb909e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb909f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59deef6a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb90a0-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb90a1-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59e5c7c2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb90a0-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb90a1-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59e1fe4e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb90a0-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb90a1-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59e0a09e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb90a2-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb90a3-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59e20ede-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb90a2-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb90a3-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59db4db0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb90a2-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb90a3-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59d84af2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb90a4-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb90a5-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59e20d44-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb90a4-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb90a5-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59dc61e6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb90a4-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb90a5-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59d904d8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb90a6-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb90a7-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59e14d8c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb90a6-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb90a7-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59dc3a54-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbbb90a6-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbbb90a7-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/59dbcfb0-dec1-11e9-aa72-0242c0a80002> )
    }
    ?procedurestap ?p ?o .
  }
}