PREFIX dossier: <https://data.vlaanderen.be/ns/dossier#>
PREFIX besluitvorming: <http://data.vlaanderen.be/ns/besluitvorming#>
DELETE {
  GRAPH ?g {
    ?dossier ?p1 ?o1 .
    ?besluitvormingsaangelegenheid ?p2 ?o2 .
  }
}
WHERE {
  GRAPH ?g {
    VALUES (?dossier) {
     (<http://themis.vlaanderen.be/id/dossier/80e93c5e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e652e6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e13eaa-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a3c732-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a9a8e6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/810a1fbe-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f441c6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f92af6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eccd74-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ea67e6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e685d6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80de10ae-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80dc4008-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80d65378-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a6a998-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a07334-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8099cc96-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8099cae8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81198e18-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/810f687a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/811180e2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/810f65d2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ff5b6a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e68a2c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80dcb48e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80d7f5a2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a1f97a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807653ba-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807651e4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ac5cc6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/810b7f3a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f996f8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f5fb4c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f5ed96-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ecc982-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eeddc6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ee4c8a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80dcd770-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ac66e4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ac61da-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/816360f6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8121ade6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8106e63c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81000f56-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f44388-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f44626-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f2ac30-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a07546-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a06b64-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8099ce3a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/816206ac-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/811f3048-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8112fa44-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8112efb8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8112a63e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8112a79c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/810a2f2c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81065fdc-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81034b62-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f976a0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f81fa8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f0e6b6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f0622c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e4f216-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80d854fc-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a06f1a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807dc33e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807dbd3a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807dc83e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ac6bc6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/810f6078-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81199020-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81119da2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8100385a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f8834e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f57e24-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ef0328-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ee255c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e4f3d8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e5ca38-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80dcd856-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80d50c02-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80d6de6a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80d69d1a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807dc51e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807dd40a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807dd1f8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ac7580-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ac70a8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/812ccfdc-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8101b716-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81012c42-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ffbac4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f597d8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f44888-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eceab6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e4f5b8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e681e4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80d803a8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80d63a32-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/809a0292-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807dd644-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807dca3c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80765504-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8161b030-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8122b3b2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8127b92a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81086dd6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f923f8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ef01ac-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ecca72-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e4f77a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80dcd946-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80da1152-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80d4b6da-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a0de6e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80836aaa-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807dd824-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ac7bac-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81086c1e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/815f8152-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8159951c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/812e0faa-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81199444-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81123a6e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/810b9dee-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8100129e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e5010c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e4f9dc-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e4ff4a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e4fd74-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e980b0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e832c8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e5c4b6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80d70a98-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80d51c9c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a5a412-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ad674c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80936bbc-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8191128a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/812a3632-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8119a4ca-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81175260-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/811178c2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8110bd88-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/810a8cb0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81012102-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ff59bc-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f539f0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f79bc8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f63a62-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80edac4e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e502b0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eb9d0a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e9d84e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e7f3d0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e57c5e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80de391c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80dd58b2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80d62600-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a3f108-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80a56f06-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807ff4f6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807dd946-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/807656e4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ed242c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/818f0882-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8183014a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8161f626-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81636754-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/815b9c5e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8144acf6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813185ea-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/812f697c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/812a129c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81286dc0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8121312c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81212fe2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/811d23fc-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81171462-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/810f7ebe-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8113e580-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8112e360-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81087006-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/810983c4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/810015d2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8102bf62-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81025eb4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8101744a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8100ff24-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81001d34-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/810046ba-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ffcd20-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80feffbc-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80fa8cca-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f97574-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f672ca-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f4d1cc-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f2b572-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80f02b9a-dec2-11e9-aa72-0242c0a80002>)
    }
      ?dossier dossier:Dossier.isNeerslagVan ?besluitvormingsaangelegenheid;
             ?p1 ?o1  .
      ?besluitvormingsaangelegenheid a besluitvorming:Besluitvormingsaangelegenheid;
                                   ?p2 ?o2  .
  }
}
