PREFIX org: <http://www.w3.org/ns/org#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX adms: <http://www.w3.org/ns/adms#>

INSERT DATA {
   GRAPH <http://mu.semte.ch/graphs/public> {
     <http://themis.vlaanderen.be/id/gebruiker/10afadbc-6d4c-474e-a1e5-3f8e1af99948> a foaf:Person ;
     mu:uuid "10afadbc-6d4c-474e-a1e5-3f8e1af99948" ;
     foaf:firstName "Kanselarij" ;
     foaf:familyName "Test" ;
     foaf:account <http://themis.vlaanderen.be/id/account/837b7934-261e-4782-a51d-9b058810cf90> .

     <http://themis.vlaanderen.be/id/account/837b7934-261e-4782-a51d-9b058810cf90> a foaf:OnlineAccount ;
     mu:uuid "837b7934-261e-4782-a51d-9b058810cf90" ;
     foaf:accountServiceHomepage <https://github.com/kanselarij-vlaanderen/mock-login-service> ;
     foaf:accountName "kanselarij-test" .

     <http://themis.vlaanderen.be/id/lidmaatschap/b95500d6-9b42-4d73-8874-e0081e0a90a0> a org:Membership ;
     mu:uuid "b95500d6-9b42-4d73-8874-e0081e0a90a0" ;
     org:member <http://themis.vlaanderen.be/id/gebruiker/10afadbc-6d4c-474e-a1e5-3f8e1af99948> ;
     org:role <http://themis.vlaanderen.be/id/gebruikersrol/ab39b02a-14a5-4aa9-90bd-e0fa268b0f3d> ;
     org:organization <http://themis.vlaanderen.be/id/organisatie/40df7139-fdfb-4ab7-92cd-e73ceba32721> .
   }
}

;

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/system/users> {
    <http://themis.vlaanderen.be/id/gebruiker/10afadbc-6d4c-474e-a1e5-3f8e1af99948> adms:status <http://themis.vlaanderen.be/id/concept/43ba4953-3484-4ec7-9741-6e709befc531> .
    <http://themis.vlaanderen.be/id/lidmaatschap/b95500d6-9b42-4d73-8874-e0081e0a90a0> adms:status <http://themis.vlaanderen.be/id/concept/43ba4953-3484-4ec7-9741-6e709befc531> .
  }
}
