PREFIX dossier: <https://data.vlaanderen.be/ns/dossier#>
PREFIX besluitvorming: <http://data.vlaanderen.be/ns/besluitvorming#>
DELETE {
  GRAPH ?g {
    ?dossier ?p1 ?o1 .
    ?besluitvormingsaangelegenheid ?p2 ?o2 .
  }
}
WHERE {
  GRAPH ?g {
    VALUES (?dossier) {
     (<http://themis.vlaanderen.be/id/dossier/813a171e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813aee32-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813aab98-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813acf1a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813dfdb6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813f7dc6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813ae234-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813a0aa8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813aebe4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813a1a02-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813abcbe-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813ae8b0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813ae572-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813aed10-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8139e0fa-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8139f52c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813d2134-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8139df10-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813f7b78-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813b8ebe-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813d1ce8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813cbb9a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813d1f40-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8139e2d0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813ae680-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813b9ad0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813b08a4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813dc6d4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813fb264-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813b70e6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813df514-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8146f132-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813b7992-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813abf34-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813b1e34-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813c5100-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813cc702-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813be328-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813cea20-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813b776c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813b151a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813df244-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813b32de-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813af724-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813d4268-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813b1cf4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813c7acc-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813d2ab2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813cf79a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813ae78e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813b8cca-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813b9c9c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813c3d96-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813b98f0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813aba2a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813b13ee-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813b6fd8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813daea6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813c4502-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813b6ede-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813ce642-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8140e170-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813b3b8a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8140b52e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81438c72-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813c0ba0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813bad40-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8141c752-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/814015ce-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813ced18-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813b6dc6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813be1de-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813c3bb6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813bd662-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813c1ad2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813cbdde-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813d3e76-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813e1daa-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813c520e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813c4f84-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813c7e46-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813c7d10-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813c56fa-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813ecaf2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813c476e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813df9ce-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813cf60a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813cf01a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813c9142-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813c2a2c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8143ff36-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81411a6e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81419cf0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813d2c88-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813d3674-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813dc5e4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813dfadc-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813dda5c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813f4b3a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8140139e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813e3f7e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813e3e70-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813ccd1a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813df712-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813c5aa6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813cf8da-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813e7f20-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813e2e62-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813c8472-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813e8b14-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813c827e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813e25c0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813cca72-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813ccc34-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813cc450-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813ecbf6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813e49ec-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813e87d6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813d021c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813e7796-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8140fbf6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813ec7d2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8141adda-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/814ba132-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/814ba3a8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813d4d58-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813eaf18-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813ec9da-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813e21ba-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813e89e8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813ee866-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813d23fa-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813ed286-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8140359a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813fa9a4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813eda4c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8143ae64-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813ecd18-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813edc4a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813fc0c4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813e825e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813f123c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8143ad60-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813ed678-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813fdabe-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813f2984-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8143785e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813f4040-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/814023f2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813f20f6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813f6ee4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813fc66e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813eb328-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813eb12a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81402b04-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813f0436-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813e99ba-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813e205c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/814064de-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8140403a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8141015a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8140c46a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81411e6a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8140e94a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813f8df2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813f86f4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813eea50-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81414dea-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813fd122-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813fd000-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81405afc-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813fe004-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8140a908-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/813feea0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/814acf1e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/814277ce-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81404f12-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81400f3e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81404b2a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81417360-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81404742-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81426a36-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/814782b4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8140172c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8147f01e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8143dbaa-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81416078-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81412eaa-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81414ff2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81412676-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8147eea2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8143cb42-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81415a88-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8141628a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8141f128-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81427eae-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/81416186-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8141c158-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8140ff34-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/8142203a-dec2-11e9-aa72-0242c0a80002>)
    }
      ?dossier dossier:Dossier.isNeerslagVan ?besluitvormingsaangelegenheid;
             ?p1 ?o1  .
      ?besluitvormingsaangelegenheid a besluitvorming:Besluitvormingsaangelegenheid;
                                   ?p2 ?o2  .
  }
}
