PREFIX dossier: <https://data.vlaanderen.be/ns/dossier#>
PREFIX besluitvorming: <http://data.vlaanderen.be/ns/besluitvorming#>
DELETE {
  GRAPH ?g {
    ?dossier ?p1 ?o1 .
    ?besluitvormingsaangelegenheid ?p2 ?o2 .
  }
}
WHERE {
  GRAPH ?g {
    VALUES (?dossier) {
     (<http://themis.vlaanderen.be/id/dossier/80ec9b06-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ec836e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ec84c2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ec660e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ec87d8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eb8d1a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ec4e6c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ec4b7e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ec403e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ec444e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ebada4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eb1a4c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eb4be8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eb72f8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eb0232-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eb6fba-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eba08e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eba34a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eb3c0c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eb9e86-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eb4f62-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eb6da8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eb64d4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eb6704-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eba55c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eb37a2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eb4e4a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eacfb0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eb0066-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ead83e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eac484-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eac876-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ead596-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eac31c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eacb0a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ea989c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ea650c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eac5d8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ead24e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eae95a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ea8118-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ea826c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ea7fba-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80eaabde-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ea94e6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ea6bba-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ea5a08-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ea5134-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ea6e76-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ea66ec-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ea68fe-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ea5d32-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ea5b5c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ea588c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ea4018-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ea117e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ea3dd4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ea18ae-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ea0fd0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80ea176e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e9eb2c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e9a25c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e9e33e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e9a6b2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e9e488-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e9dc9a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e9ef00-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e9e0a0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e9df2e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e9988e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e9ab44-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e9a504-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e96c1a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e986aa-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e98c54-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e95b9e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e96b16-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e969f4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e955a4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e9680a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e958ec-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e9492e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e93736-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e91440-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e923f4-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e94460-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e8b068-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e92070-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e8fe1a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e8fa3c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e8c1de-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e8e678-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e90090-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e8e588-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e8ee84-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e8c40e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e8df7a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e8c2b0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e8d5b6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e8de80-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e8db92-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e8b7f2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e8cb34-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e8dd7c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e8a21c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e89bc8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e8a7a8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e886d8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e87e86-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e880de-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e881ec-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e79e62-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e890ce-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e7a3f8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e882dc-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e891e6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e88f84-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e88aac-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e893da-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e7a2ea-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e883d6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e88c00-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e892e0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e88d0e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e884c6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e887c8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e88e1c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e87f9e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e7e76e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e82ce2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e80a6e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e7f88a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e808fc-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e7f27c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e82698-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e82f12-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e82b84-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e7d152-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e7ea52-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e7f790-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e7ed22-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e7e62e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e80b9a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e779a0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e74188-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e75416-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e73b16-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e72130-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e6fdb8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e6ee7c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e703bc-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e6a93a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e6fbb0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e70254-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e69e72-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e705e2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e704ca-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e6ad36-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e6b128-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e6b6d2-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e6aba6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e6c8ac-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e6d414-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e6cef6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e6c9b0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e6d522-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e6a11a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e6890a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e674ec-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e67e2e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e682de-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e6681c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e6571e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e686f8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e679d8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e66678-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e6544e-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e649b8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e64b02-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e65804-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e646b6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e64df0-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e63342-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e64864-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e62dfc-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e5f29c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e63874-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e5d758-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e5c920-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e5b106-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e5b2be-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e5d5dc-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e5c2cc-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e5c81c-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e5c0f6-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e5c718-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e5b61a-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e5a5a8-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e5a396-dec2-11e9-aa72-0242c0a80002>)
     (<http://themis.vlaanderen.be/id/dossier/80e59fc2-dec2-11e9-aa72-0242c0a80002>)
    }
      ?dossier dossier:Dossier.isNeerslagVan ?besluitvormingsaangelegenheid;
             ?p1 ?o1  .
      ?besluitvormingsaangelegenheid a besluitvorming:Besluitvormingsaangelegenheid;
                                   ?p2 ?o2  .
  }
}
