PREFIX dossier: <https://data.vlaanderen.be/ns/dossier#>
PREFIX besluitvorming: <http://data.vlaanderen.be/ns/besluitvorming#>
PREFIX dct: <http://purl.org/dc/terms/>
INSERT {
  GRAPH ?g {
    ?dossier a dossier:Dossier .
    ?dossier dossier:Dossier.isNeerslagVan ?besluitvormingsaangelegenheid .
    ?besluitvormingsaangelegenheid a besluitvorming:Besluitvormingsaangelegenheid .
    ?besluitvormingsaangelegenheid dossier:doorloopt ?procedurestap .
  }
}
WHERE {
  GRAPH ?g {
    VALUES (?dossier ?besluitvormingsaangelegenheid ?procedurestap) {
      ( <http://themis.vlaanderen.be/id/dossier/dbcde010-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbcde011-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5abd7b4a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0720-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0721-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5abd624a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0722-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0723-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5abd8f86-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0724-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0725-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5abce266-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0726-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0727-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5abcf29c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0728-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0729-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5abcde10-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce072a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce072b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5abcf076-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce072c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce072d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5abd2ca8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce072e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce072f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5abd4fe4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0730-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0731-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5abda2b4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0732-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0733-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5abc5ce2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0734-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0735-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5abb7cbe-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0736-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0737-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5abb6274-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0738-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0739-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5abb68aa-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce073a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce073b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5abb7142-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce073c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce073d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5abb6594-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce073e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce073f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5abb6f3a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0740-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0741-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aba6996-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0742-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0743-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aba418c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0744-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0745-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aba6bee-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0746-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0747-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aba2486-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0748-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0749-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ababe96-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce074a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce074b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5abadff2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce074c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce074d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5abac3e6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce074e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce074f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5abaf88e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0750-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0751-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5abac148-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0752-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0753-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5abaf6c2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0754-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0755-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab9a36c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0756-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0757-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab9ab28-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0758-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0759-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5abaadd4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce075a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce075b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5abaff0a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce075c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce075d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab9f038-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce075e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce075f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab86632-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0760-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0761-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab8c3ca-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0762-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0763-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab8d2f2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0764-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0765-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab9180c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0766-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0767-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab8dcca-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0768-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0769-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab7d9e2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce076a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce076b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab7fe9a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce076c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce076d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab7a40e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce076e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce076f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab7c9ac-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0770-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0771-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab7f58a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0772-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0773-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab8034a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0774-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0775-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab6f31a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0776-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0777-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab6fe8c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0778-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0779-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab679bc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce077a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce077b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab638e4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce077c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce077d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab677a0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce077e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce077f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab5605e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0780-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0781-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab41e38-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0782-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0783-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab44188-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0784-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0785-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab32c30-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0786-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0787-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab344d6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0788-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0789-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab384e6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce078a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce078b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab3c06e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce078c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce078d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab38bbc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce078e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce078f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab2948c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0790-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0791-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab2756a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0792-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0793-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab26f70-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0794-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0795-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab15090-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0796-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0797-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab16e04-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0798-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0799-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab0c206-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce079a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce079b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aafad30-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce079c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce079d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aafc8ec-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce079e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce079f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aafa6aa-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07a0-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07a1-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab03124-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07a2-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07a3-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aaf70e0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07a4-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07a5-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5ab00712-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07a6-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07a7-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aae2834-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07a8-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07a9-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aae113c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07aa-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07ab-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aae3b1c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07ac-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07ad-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aacdbf0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07ae-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07af-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aacd344-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07b0-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07b1-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aacd07e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07b2-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07b3-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aacb986-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07b4-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07b5-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aacfffe-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07b6-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07b7-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aac2ffc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07b8-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07b9-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aa8f12a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07ba-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07bb-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aa952d2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07bc-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07bd-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aa9bb82-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07be-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07bf-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aa9bdc6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07c0-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07c1-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aa8d8a2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07c2-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07c3-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aa819da-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07c4-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07c5-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aa772d2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07c6-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07c7-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aa7b652-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07c8-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07c9-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aa7719c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07ca-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07cb-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aa7d88a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07cc-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07cd-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aa71df0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07ce-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07cf-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aa6fae6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07d0-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07d1-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aa713be-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07d2-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07d3-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aa6eb78-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07d4-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07d5-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aa6f2da-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07d6-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07d7-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aa67c24-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07d8-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07d9-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aa67eb8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07da-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07db-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aa5d01c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07dc-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07dd-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aa5d792-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07de-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07df-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aa578d8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07e0-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07e1-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aa57b30-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07e2-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07e3-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aa16978-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07e4-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07e5-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aa13246-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07e6-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07e7-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aa12198-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07e8-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07e9-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aa11a72-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07ea-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07eb-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5aa1eb78-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07ec-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07ed-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a9e540e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07ee-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07ef-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a9ceab0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07f0-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07f1-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a9c2378-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07f2-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07f3-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a9b9502-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07f4-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07f5-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a9b6e42-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07f6-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07f7-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a9b74fa-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07f8-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07f9-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a9b7c2a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07fa-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07fb-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a9ad252-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07fc-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07fd-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a99ab70-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce07fe-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce07ff-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a99c952-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0800-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0801-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a9a019c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0802-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0803-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a99a468-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0804-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0805-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a992240-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0806-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0807-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a9905f8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0808-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0809-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a9864cc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce080a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce080b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a9870d4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce080c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce080d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a97bbd0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce080e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce080f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a97a0a0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0810-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0811-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a97472c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0812-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0813-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a9797fe-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0814-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0815-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a96435e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0816-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0817-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a962748-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0818-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0819-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a951c68-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce081a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce081b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a94319a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce081c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce081d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a943d70-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce081e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce081f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a942614-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0820-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0821-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a93a6a8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0822-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0823-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a9391c2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0824-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0825-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a9376ce-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0826-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0827-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a9338b2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0828-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0829-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a930bda-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce082a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce082b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a93183c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce082c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce082d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a927a26-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce082e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce082f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a927814-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0830-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0831-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a901f1a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0832-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0833-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a9060c4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0834-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0835-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a906600-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0836-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0837-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8f4568-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0838-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0839-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8f560c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce083a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce083b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8f53dc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce083c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce083d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8e95dc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce083e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce083f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8e4d16-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0840-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0841-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8e165c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0842-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0843-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8d7332-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0844-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0845-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8daa0a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0846-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0847-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8d82a0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0848-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0849-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8d38f4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce084a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce084b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8d36b0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce084c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce084d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8d3d72-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce084e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce084f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8ceea8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0850-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0851-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8d66ee-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0852-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0853-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8d3f8e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0854-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0855-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8d3b4c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce0856-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce0857-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8ce6d8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e30-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e31-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8d6914-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e32-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e33-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8cdf76-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e34-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e35-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8d52e4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e36-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e37-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8bbf4c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e38-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e39-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8b7686-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e3a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e3b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8b5fc0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e3c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e3d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8b8d60-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e3e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e3f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8b06e2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e40-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e41-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8c263a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e42-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e43-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8b91de-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e44-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e45-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8b882e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e46-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e47-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8afdf0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e48-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e49-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8b3fc2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e4a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e4b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8bb43e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e4c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e4d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8af526-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e4e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e4f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8ba37c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e50-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e51-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8a7cf4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e52-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e53-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8a4f86-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e54-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e55-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8a4798-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e56-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e57-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8a790c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e58-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e59-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8a19b2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e5a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e5b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a888c64-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e5c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e5d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a877f36-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e5e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e5f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a86c5c8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e60-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e61-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8593c4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e62-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e63-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a85a3be-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e64-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e65-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a85b28c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e66-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e67-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a852358-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e68-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e69-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a85254c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e6a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e6b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8466b6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e6c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e6d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8486e6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e6e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e6f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8491d6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e70-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e71-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a846fe4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e72-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e73-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a83e13c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e74-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e75-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a83b356-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e76-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e77-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a83e402-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e78-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e79-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a83e6d2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e7a-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e7b-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a82ca04-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e7c-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e7d-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a82e0a2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e7e-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e7f-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a815caa-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e80-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e81-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a8153b8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e82-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e83-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a80a292-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/dossier/dbce2e84-7d58-11ed-ab12-455300b30cde> <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/dbce2e85-7d58-11ed-ab12-455300b30cde> <http://kanselarij.vo.data.gift/id/procedurestappen/5a7f1d28-dec1-11e9-aa72-0242c0a80002> )
    }
    ?procedurestap ?p ?o .
  }
}