PREFIX dossier: <https://data.vlaanderen.be/ns/dossier#>
PREFIX besluitvorming: <http://data.vlaanderen.be/ns/besluitvorming#>
INSERT {
  GRAPH ?g {
    ?besluitvormingsaangelegenheid dossier:doorloopt ?procedurestap .
  }
}
WHERE {
  GRAPH ?g {
    VALUES (?besluitvormingsaangelegenheid ?procedurestap) {
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D538927-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5aee03b4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D538927-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae7da8e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54866E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5aed4000-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54866E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5aebf8ee-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5195A8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5aed54f0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5195A8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae95f4e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D539FE3-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5aedf68a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D539FE3-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae775e4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D535802-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5aed8524-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D535802-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae6fc36-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53E52F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5aed5734-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53E52F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adf6386-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54E5FB-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5aeda2a2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54E5FB-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5aaee260-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D542067-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5aedcc0a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D542067-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae0e0c6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D517F64-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5aed8ab0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D517F64-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae1c95a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D554144-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5aed8c86-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D554144-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae861c0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D520402-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5aebd896-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D520402-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae75618-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D531F9B-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5aebc3b0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D531F9B-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae1bbe0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52BCEE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5aeb8210-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52BCEE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae5aa84-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54D236-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5aebd4d6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54D236-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae59b34-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D536A86-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5aebd6ca-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D536A86-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae74c90-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50A491-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae953be-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50A491-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae1b97e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5607A0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae91110-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5607A0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae5ae4e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D563555-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae922ea-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D563555-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae373a4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5180AE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae94f9a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5180AE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae1b730-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D521794-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae93f6e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D521794-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae178ce-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50FD0A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae91318-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50FD0A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5add6a0e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51C9C4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae928a8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51C9C4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae413fe-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52999E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae80f36-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52999E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adf8ff0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54C336-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae7fe6a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54C336-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5add1a68-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D514774-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae80d38-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D514774-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adf920c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D527A54-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae8478a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D527A54-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae00ffc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53F65F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae858ba-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53F65F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae4166a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D562BC2-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae84d66-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D562BC2-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae4cb32-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D527C48-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae85478-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D527C48-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae14944-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D512371-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae75104-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D512371-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae3a0c2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D560A71-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae703ca-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D560A71-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae0d0ae-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D535529-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae79baa-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D535529-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae5bd8a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5636BC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae768d8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5636BC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae3930c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52AF42-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae748a8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52AF42-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adc4a3e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54A5A4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae67d10-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54A5A4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae1395e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D563113-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae610b4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D563113-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae2650e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52304F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae65452-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52304F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adf266e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D523617-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae67072-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D523617-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae1dd3c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54AA0F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae66e7e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54AA0F-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adc89cc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55F24C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae60218-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55F24C-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ade9a6e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D518DCE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae5b538-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D518DCE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ad1659c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50A59E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae5b2f4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50A59E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5add5dc0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D513FF4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae576d6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D513FF4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adef84c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50B20B-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae51a6a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50B20B-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae10a7e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D563CCA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae51ec0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D563CCA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae110be-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D548FF6-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae4f440-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D548FF6-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adb95da-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D522784-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae4fba2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D522784-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae0e2f6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55563E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae54120-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55563E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adf7ca4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52D0D0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae52e1a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52D0D0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ad98042-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51D9B5-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae4c3e4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51D9B5-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5aad9d10-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D543F60-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae474f2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D543F60-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae0dee6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50B66B-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae468fe-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50B66B-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5add1248-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52A218-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae48046-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52A218-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae13094-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50DF14-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae46b06-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50DF14-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adf0828-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51B60A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae46d86-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51B60A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae15344-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D531E78-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae4571a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D531E78-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ac6763c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54AE0A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae47998-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54AE0A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adc522c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D525971-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae47e20-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D525971-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae1d1a2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D558082-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae3fe96-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D558082-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adf1f48-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D556CA0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae3e8de-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D556CA0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae1b1ea-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D559825-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae407a6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D559825-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5acc79f6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D56223B-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae37e12-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D56223B-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae16852-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51235D-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae3681e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51235D-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adf8302-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50CAF6-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae3414a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50CAF6-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ad80816-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5192F6-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae30f36-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5192F6-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adc598e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51AB9D-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae2da7a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51AB9D-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adf4d9c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55EB45-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae306da-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55EB45-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adc3490-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5323A0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae308e2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5323A0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adc7ec8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51848D-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae2735a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51848D-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ade025c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51F3CC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae25dc0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51F3CC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adce44e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52EFD4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae04fd0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D52EFD4-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ad8e646-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D541CE2-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae1a376-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D541CE2-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adbd018-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5499BB-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae10344-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5499BB-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adb2262-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55C6AA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae15fb0-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55C6AA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ad4dfe2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D537AC6-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae19d9a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D537AC6-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adc7702-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50EDEC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ae12b8a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50EDEC-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ad9f748-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D545EA0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adf65ca-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D545EA0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ad67dd4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D512366-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adf7a6a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D512366-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ad8e3b2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D510250-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adf40cc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D510250-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ada8a14-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D514D51-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adf53dc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D514D51-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ad693c8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5520BB-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adf86a4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5520BB-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adbd4aa-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55D9BB-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adf3ec4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55D9BB-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ad9ba3a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5527B8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adeaff4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5527B8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ad5c628-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55978E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adeb77e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D55978E-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ad62e7e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53EB32-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adf8b36-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53EB32-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ada8f6e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D533520-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adebed6-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D533520-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ada4522-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54B314-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adddc32-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54B314-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ad9c2fa-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D523DBE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ade0e64-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D523DBE-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ad765dc-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54AEA0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ade1a44-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54AEA0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ad71d48-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D545540-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ade23ae-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D545540-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ac30876-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D541648-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ade185a-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D541648-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5acf95fa-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50CCE0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5add5032-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D50CCE0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ad70722-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54CCB5-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5add5b72-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D54CCB5-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ad8c92c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5542CA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5add2b48-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D5542CA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ad654a8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D561E52-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5add3a70-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D561E52-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ad763ac-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53C5B2-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5add490c-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D53C5B2-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ad6201e-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51C5AA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5add4434-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D51C5AA-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5acfbbac-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D522A4A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adbb358-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D522A4A-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ad77fc2-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D524EF8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adbc0c8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D524EF8-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5ad7a7f4-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D522BD0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5adb14e8-dec1-11e9-aa72-0242c0a80002> )
      ( <http://themis.vlaanderen.be/id/besluitvormingsaangelegenheid/8D522BD0-411C-11ED-BB35-EE395168DCF7> <http://kanselarij.vo.data.gift/id/procedurestappen/5abe644c-dec1-11e9-aa72-0242c0a80002> )
    }
    ?procedurestap ?p ?o .
    FILTER NOT EXISTS { ?besluitvormingsaangelegenheid dossier:doorloopt ?procedurestap . }
  }
}