PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>
PREFIX dossier: <https://data.vlaanderen.be/ns/dossier#>
PREFIX besluitvor: <https://data.vlaanderen.be/ns/besluitvorming#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX prov: <http://www.w3.org/ns/prov#>

DELETE {
  GRAPH <http://mu.semte.ch/graphs/organizations/kanselarij> {
    ?decisionmakingFlow ?dcmfP ?dcmfO .

    ?case ?cP ?cO .

    ?subcase ?scP ?scO .
    ?scS ?scP_ ?subcase .
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/organizations/kanselarij> {
    VALUES ?decisionmakingFlowId { "8D5686A8-411C-11ED-BB35-EE395168DCF7" "8C806F51-411C-11ED-BB35-EE395168DCF7" }
    ?decisionmakingFlow mu:uuid ?decisionmakingFlowId .

    ###
    # Stuff we need to delete
    ?case dossier:Dossier.isNeerslagVan ?decisionmakingFlow .
    ?decisionmakingFlow dossier:doorloopt ?subcase .

    OPTIONAL { ?decisionmakingFlow ?dcmfP ?dcmfO }

    OPTIONAL { ?case ?cP ?cO }

    OPTIONAL { ?subcase ?scP ?scO }
    OPTIONAL { ?scS ?scP_ ?subcase }
  }
}
