PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX dct: <http://purl.org/dc/terms/>

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?subcaseType ?p ?o .
  }
}
INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?newUrl ?p ?o .
  }
}
WHERE {
  VALUES (?subcaseType ?newUrl) {
      (<http://example.com/step/bdba2bbc-7af6-490b-98a8-433955cfe869> <http://themis.vlaanderen.be/id/concept/procedurestap-type/bdba2bbc-7af6-490b-98a8-433955cfe869>)
      (<http://example.com/step/6f7d1086-7c02-4a80-8c60-5690894f70fc> <http://themis.vlaanderen.be/id/concept/procedurestap-type/6f7d1086-7c02-4a80-8c60-5690894f70fc>)
      (<http://example.com/step/7b90b3a6-2787-4b41-8a1d-886fc5abbb33> <http://themis.vlaanderen.be/id/concept/procedurestap-type/7b90b3a6-2787-4b41-8a1d-886fc5abbb33>)
  }
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?subcaseType ?p ?o .
  }
}