PREFIX besluitvorming: <https://data.vlaanderen.be/ns/besluitvorming#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

INSERT {
  GRAPH ?g {
    ?minutes ext:isReportOrMinutes true .
  }
} WHERE {
  GRAPH ?g {
	  ?minutes a ext:Notulen .
		FILTER NOT EXISTS { ?minutes ext:isReportOrMinutes true . }
	}
}
