DELETE { GRAPH ?g { ?newsItem ?p ?o } }
WHERE {
  VALUES (?newsItem) {
    (<http://themis.vlaanderen.be/id/nieuwsbrief-info/62D009978E6C4430A8898B60>)
    (<http://themis.vlaanderen.be/id/nieuwsbrief-info/628DDA2E2071A7D754F17C2E>)
    (<http://themis.vlaanderen.be/id/nieuwsbrief-info/62752BF51C4A193816C30A57>)
    (<http://themis.vlaanderen.be/id/nieuwsbrief-info/6274C5C61C4A193816C30949>)
    (<http://themis.vlaanderen.be/id/nieuwsbrief-info/6274C4EB1C4A193816C30948>)
    (<http://themis.vlaanderen.be/id/nieuwsbrief-info/626B934B1C4A193816C2FFDB>)
    (<http://themis.vlaanderen.be/id/nieuwsbrief-info/61FA5E13D5F0FAFA87AFA98A>)
    (<http://themis.vlaanderen.be/id/nieuwsbrief-info/61F28814D5F0FAFA87AFA5DD>)
    (<http://themis.vlaanderen.be/id/nieuwsbrief-info/61F10D78D5F0FAFA87AFA57C>)
    (<http://themis.vlaanderen.be/id/nieuwsbrief-info/61B897A0364ED9000900158F>)
    (<http://themis.vlaanderen.be/id/nieuwsbrief-info/61B89877364ED90009001590>)
    (<http://themis.vlaanderen.be/id/nieuwsbrief-info/61B89645364ED9000900158D>)
    (<http://themis.vlaanderen.be/id/nieuwsbrief-info/61B895E9364ED9000900158C>)
    (<http://themis.vlaanderen.be/id/nieuwsbrief-info/61B89342364ED90009001587>)
    (<http://themis.vlaanderen.be/id/nieuwsbrief-info/61938192364ED90008000161>)
    (<http://themis.vlaanderen.be/id/nieuwsbrief-info/618557BC364ED900080008B2>)
    (<http://themis.vlaanderen.be/id/nieuwsbrief-info/617BA1CA364ED900080007DD>)
    (<http://themis.vlaanderen.be/id/nieuwsbrief-info/615FF0F1364ED90009000279>)
    (<http://themis.vlaanderen.be/id/nieuwsbrief-info/60F132D5364ED900080017BC>)
    (<http://themis.vlaanderen.be/id/nieuwsbrief-info/60CA3CEE364ED90008000435>)
    (<http://themis.vlaanderen.be/id/nieuwsbrief-info/60C30715364ED90008000096>)
    (<http://themis.vlaanderen.be/id/nieuwsbrief-info/60C30441364ED90008000092>)
    (<http://themis.vlaanderen.be/id/nieuwsbrief-info/60C30239364ED90008000091>)
    (<http://themis.vlaanderen.be/id/nieuwsbrief-info/60C30198364ED9000800008E>)
    (<http://themis.vlaanderen.be/id/nieuwsbrief-info/60929DEC364ED9000800001B>)
    (<http://themis.vlaanderen.be/id/nieuwsbrief-info/60929EBF364ED9000800001C>)
    (<http://themis.vlaanderen.be/id/nieuwsbrief-info/6092AE2E364ED90008000025>)
    (<http://themis.vlaanderen.be/id/nieuwsbrief-info/60800E21364ED900080004EE>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6066BDF0364ED9000800063D>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/604A2F5133914000080006B2>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6041E61733914000080003E9>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6041E59033914000080003E4>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6001AAB96B34EF0008000069>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5FDC650B6B34EF0008000DB6>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5FDA0BA86B34EF0008000B27>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5FD8ADC86B34EF0008000A6D>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5FD323E26B34EF000800015D>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5FC9EEE120B6670008000133>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5F99740D5B1AD200080003BD>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/7522a5fe-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/74f99c90-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/757b1b3a-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/7573d35c-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/75395ca4-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/74eb23c2-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/74f263da-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/757160ea-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/755b41f2-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/7569f4ea-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/757fed86-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/7529fe4e-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/75032d64-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/74da7842-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/756c68a6-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/75650a3e-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/757647a4-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/756ee04a-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/750f3afa-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/754f3902-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/7556689e-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/7547f372-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/74d338de-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/7562966e-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/7540b832-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/756022e4-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/751b5ed4-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/75677f12-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6e694f2e-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6f6a2628-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/4e01b208-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/41911856-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/4189da1e-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/24843dd8-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/2458c0fe-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/247a9170-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/036c51e4-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/f6d6c1e4-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/e01408b8-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/c481dc10-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/c477efe8-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/bfc92566-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/b57da528-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/b552130e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/b7c00dc6-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/b2ca20e0-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/8f17c242-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6ffa0078-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6ad27c88-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/685e3f32-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/61246570-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6111458a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/61113090-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6106b9c6-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/61067e84-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60f047e0-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60c633b0-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60c384a8-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60be229c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60bc3fa4-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60afb7ac-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60acfc1a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60a82726-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60a2e504-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/609df4ea-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/605c9dba-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6078a6ea-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6078d232-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/607937ae-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6076a250-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60771a6e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6077b866-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6077a4b6-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/607987d6-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60786c3e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6078f348-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6076fe30-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60772fae-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60783322-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6078dfd4-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6076773a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6076eb98-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60787fbc-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/607740fc-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60791cf6-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6076841e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6079969a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60784c04-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60776cbc-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60797732-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6079b10c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6077c856-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60775308-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60775eac-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6078c454-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6079d790-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60785c62-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6077902a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60794988-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60777f86-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6079e5f0-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6076df7c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6076c35c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60770f2e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6079660c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6079a540-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/607892ae-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6078b6ee-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6077df3a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60769742-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6076d0ea-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60783e6c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60792c14-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6076636c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6079c43a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6076b27c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60795810-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6059b668-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6062f87c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5fb602e8-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5fdad744-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5fdac06a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5fa534ae-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5fd2835a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5f9061dc-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5fc5d2cc-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5fc06bd4-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5fbf776a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5fff26f8-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5f477ca6-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5f47af6e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5eaf8cb6-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e90b318-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e90a242-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5f479646-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5f478890-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5f474d94-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5f473ebc-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5f47baa4-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5f4ca924-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e90c1fa-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5f4cc8a0-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5f47a1cc-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5f4758f2-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5f4770ee-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5f4cb4d2-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5f47cf9e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5ea1a9ca-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5eaf1768-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5eaed618-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5f21376c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e7c240c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e59d618-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e5eb3d6-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e64620e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e599608-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e648540-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e5b91f6-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e5f523c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e597466-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e598ad2-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e59ba70-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e597fb0-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e5f33f6-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e59c60a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e646c36-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e59a184-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e5f886a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e5b9fb6-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e5b3aee-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e5f2708-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e5b51c8-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e5b5cfe-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e5edc1c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e59468a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e59667e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e5f5b06-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e5f46ac-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e5ec178-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e647776-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e595d32-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e59af26-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e5ee9d2-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e5ef5f8-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e5f9652-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e5f753c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e5b46a6-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e5f6b96-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e59e180-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e5f1416-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e5951fc-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e5fa6e2-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e41ada4-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e42826a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e41a46c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4dff50-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e464bf2-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e42fb82-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e43279c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e42efe8-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e45c592-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e410aa2-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4ae6f8-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e47fd94-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e47b7bc-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4a632c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4aaa58-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e40ed9c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4b1312-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e46c05a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4df42e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e41d4e6-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e46b042-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e46a49e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e42aa6a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e47a998-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e47821a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e424f70-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4c1956-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4d6b9e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4d899e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e471988-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4a8c26-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e434d80-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e45116a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e42c5ea-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4dc1a2-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e419864-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e414fd0-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e42d3d2-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e45df6e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4166be-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e41391e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e479e44-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4b29ce-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4377c4-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e417f6e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4b1e5c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e431590-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e470ba0-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e468d6a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e454f40-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4ac40c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e45d37a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4c452a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4b4044-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e45f6e8-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e46629a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4b0778-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e50a3cc-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e47d68e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e483cdc-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e433444-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e590aa8-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4db3f6-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e46021e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e467c76-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4a955e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e458244-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e45abe8-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e430bc2-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e41e0ee-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e42e458-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4aa116-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e42a100-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4c34d6-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e456b38-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e466e2a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e418aae-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e45bc32-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e43835e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4b5e6c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4268b6-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e46e4cc-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4da29e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e46f002-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4b6f2e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e47308a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e42441c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e46fdc2-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e476672-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e42976e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e412dd4-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4d76f2-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e415b60-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e45a08a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e473e2c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4a7e84-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e454126-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4c0470-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4deb5a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e439c5e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e461c18-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e47e44e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4ab886-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e42768a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e48316a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e592d80-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4ad00a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4a4a22-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e474d54-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4adb4a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e41445e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e46571e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e46ce38-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4808e8-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e451cbe-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e458dde-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4640a8-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e472536-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e45eb94-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e43b5ae-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4be814-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e436022-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4576be-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e43a7e4-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4825f8-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e47efca-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e41bb3c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4c2716-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e46354a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4c533a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4d974a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e431edc-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e58fcfc-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e460d7c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e58f1b2-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4a57ba-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e462794-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e47743c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e42b820-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4bf340-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e48143c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e46d98c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4535c8-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4a70e2-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4758b2-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e43c36e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e591f3e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e5913e0-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e469922-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4171ea-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e425d26-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e455f80-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4d4fe2-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4b50b6-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4d5dc0-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e41c6e0-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e41186c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e41ec6a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4af4cc-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e48de80-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e49ae5a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e49a2ac-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e49bc42-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e490c98-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e49d308-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e49e5dc-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e495892-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e493d1c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e486dd8-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e49820e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e49c7be-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e496648-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e487954-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e3b5daa-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e48d520-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e48b748-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e485dac-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e491f3a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e3b468a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e489e70-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e498d58-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e3b72fe-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e48ab4a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e499924-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e492d04-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e48e9ca-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e49dc40-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e49487a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4884b2-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e48c7b0-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e3b51fc-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5db79006-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5dc7eca8-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e1d193a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e0c972c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e1c72dc-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e0c8a20-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e1ccf8e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e1d41b2-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e0c4678-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e0c2fc6-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5dfa3aa0-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e1c949c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e1d5274-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e1d32f8-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e1ca680-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e1cbeea-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5dfa2826-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e1cde3e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e1d2614-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e1cfb9e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e0c2300-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e1d0c74-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e0c6374-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e1c875e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e0c56b8-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e0c7058-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e1ceb0e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e1baaaa-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e1b9dda-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e1bbb30-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e21cf34-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e22aa44-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e2245cc-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5df51d04-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5df45360-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5df4165c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5df43254-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5df46896-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5df4e230-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5df47c78-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5df4f2d4-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5df50e68-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5df4ffd6-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5df42386-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5df4c2b4-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5df49a46-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5df44258-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5df52dee-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5df4b3dc-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5df407ac-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5df3da8e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5df4cf8e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5df4a720-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/e4e88000-0fe2-11eb-9a42-a101b41f0404>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/e4eaf100-0fe2-11eb-9a42-a101b41f0404>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/e4ec5090-0fe2-11eb-9a42-a101b41f0404>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5fe6e282-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5ecce59a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60ba0f0e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4dcd1e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6021891e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6138d8f2-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/611f0486-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/603afbd8-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/603144b2-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/e403a74e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5effd19e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5f583906-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e5ece20-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60c82dd2-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60c5de60-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5ed32004-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6139ba9c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5fe268e2-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5fe6d922-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6077d116-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/613972b2-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/600c4f04-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60306718-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/61389e64-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/52fc7dec-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60a9baf0-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6139ae44-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5ecef6a0-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/605cfb52-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5df02bc8-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e40f8e6-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/604fe124-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60236478-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e439100-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5f6a8a34-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/61391510-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/7d0a8f30-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6106231c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6139ecba-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5f4713a6-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5fb52f3a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60790ce8-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/61387a4c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4369a0-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5dfb4e40-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/74ce5c38-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4892d6-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e434218-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/61190d4c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5ff9945e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5f276e7a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/606e7b70-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5ed0177e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/603b8a30-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/605d1b50-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e667292-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60dbdd6e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60dc0bae-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5febe1ce-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/612706ea-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6139c6cc-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5f472fbc-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5f1b1b52-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e478d78-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/a686b1c2-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/2e9f3b38-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/b1623102-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5f2603e6-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e5b81ca-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4e0fcc-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5ff798ac-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/613a0268-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4ddf70-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/613888f2-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5df9f356-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6076582c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/61194a00-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6083252a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6138eae0-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5ed3fc40-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e50b0c4-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4971ba-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6138c22c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/d50bf2a0-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6138b8d6-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5f704b9a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/303158b4-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/613a108c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/61397ed8-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5fa63df4-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6138acc4-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6082e8f8-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5f20bd5a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e787442-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5f6fdb88-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/61394f26-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/605e65c8-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/611e75a2-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/609ed3b0-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5df9fd92-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5fdc2d56-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/68f49332-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e410228-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60296bde-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/607e0036-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6138f986-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6139d2b6-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/d5526410-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60d59de6-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/61399b7a-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5f4764dc-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60a6979e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e6492ec-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/61398da6-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5f4721e8-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4d4484-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/613931e4-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5dfa0e22-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/605d2e7e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5ed3f1b4-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60d86a1c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/61396402-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60473bc8-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6138cb6e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e5b6a8c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/615831e8-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/613a1d70-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e452830-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5fa198f8-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/75321df4-dec2-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/605d24d8-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5fa6472c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6082d1b0-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6139f908-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5fc7ab60-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/60779912-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/606e8f52-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6139debe-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e5f03e0-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5ea4eda6-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5febd0e4-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6029b29c-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/6139431e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/605e5614-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e48fbfe-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e4e190e-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5e47c414-dec1-11e9-aa72-0242c0a80002>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5DA0742D1688400008000016>)
    (<http://kanselarij.vo.data.gift/id/nieuwsbrief-infos/5DD659275084E7000800001D>)
  }
  GRAPH ?g { ?newsItem ?p ?o }
}
