PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX pub: <http://mu.semte.ch/vocabularies/ext/publicatie/>
PREFIX subm: <http://mu.semte.ch/vocabularies/ext/submissions/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dossier: <https://data.vlaanderen.be/ns/dossier#>
PREFIX besluitvorming: <https://data.vlaanderen.be/ns/besluitvorming#>

DELETE {
  GRAPH ?g {
    ?resource ?veldPredicate ?oldVeld .
  }
}
INSERT {
  GRAPH ?g {
    ?resource ?veldPredicate ?newVeld .
  }
}
WHERE {
  GRAPH ?g {
    ?resource a ?type .
    ?resource ?veldPredicate ?oldVeld .
    ?resource ?createdPredicate ?created .
  }
  
  FILTER(?created >= "2024-01-01T00:00:00"^^xsd:dateTime)

  VALUES
    (?type                                        ?veldPredicate             ?createdPredicate)
  {
    (dossier:Dossier                              besluitvorming:beleidsveld dcterms:created)
    (besluitvorming:Besluitvormingsaangelegenheid besluitvorming:beleidsveld besluitvorming:openingsdatum)
    (dossier:Procedurestap                        besluitvorming:beleidsveld dcterms:created)
    (subm:Indiening                               besluitvorming:beleidsveld dcterms:created)
    (pub:Publicatieaangelegenheid                 pub:beleidsveld            dcterms:created)
  }

  VALUES (?oldVeld ?newVeld) {
    (<http://themis.vlaanderen.be/id/beleidsdomein/e2ccf3f9-6b1f-4b32-9e76-501999c51788> <http://themis.vlaanderen.be/id/beleidsdomein/8fee5169-0630-4413-b849-e87a4e5fb590>)
    (<http://themis.vlaanderen.be/id/beleidsdomein/a41f29a9-7781-4419-a821-fd3bd183c7ba> <http://themis.vlaanderen.be/id/beleidsdomein/8fee5169-0630-4413-b849-e87a4e5fb590>)
    (<http://themis.vlaanderen.be/id/beleidsdomein/98a3acec-51f2-4b6a-a1e1-6b6166d80d2e> <http://themis.vlaanderen.be/id/beleidsdomein/8fee5169-0630-4413-b849-e87a4e5fb590>)
    (<http://themis.vlaanderen.be/id/beleidsveld/e4dab90c-bb3a-47c5-abfc-802ddb55480d> <http://themis.vlaanderen.be/id/beleidsveld/ce58f92f-7ed9-4ff3-9733-5f8eb1de5e39>)
    (<http://themis.vlaanderen.be/id/beleidsveld/4d73b772-ccfa-4bd8-bd45-6722b1972a1a> <http://themis.vlaanderen.be/id/beleidsveld/6a6b62cf-c583-4cc0-9350-33f471b4848f>)
    (<http://themis.vlaanderen.be/id/beleidsveld/9bae7bf3-3851-4447-b457-5af1b0c82925> <http://themis.vlaanderen.be/id/beleidsveld/9fa3a15a-4f0d-49d6-8797-7bdfe8ea841b>)
    (<http://themis.vlaanderen.be/id/beleidsveld/82883c33-57c8-4e67-9669-53ef7f960b51> <http://themis.vlaanderen.be/id/beleidsveld/187f47a9-98a3-474c-86d4-1cb009d2fc5c>)
    (<http://themis.vlaanderen.be/id/beleidsveld/890bcc01-a3f2-40de-954b-92ea3d958784> <http://themis.vlaanderen.be/id/beleidsveld/34b0b777-2188-45b3-957e-d3cb285376f2>)
    (<http://themis.vlaanderen.be/id/beleidsveld/5a9c8b50-1d07-4bcb-9dd8-f1d041437a46> <http://themis.vlaanderen.be/id/beleidsveld/408f772f-cff3-49ce-8686-e673ff345f12>)
    (<http://themis.vlaanderen.be/id/beleidsveld/581845a0-0a25-4e43-89d6-7863572aeb6c> <http://themis.vlaanderen.be/id/beleidsveld/dc205265-59b4-4d93-abe7-a1d6d9868661>)
    (<http://themis.vlaanderen.be/id/beleidsveld/106408c9-ec8e-42cf-9e8e-6a8e7ef537b1> <http://themis.vlaanderen.be/id/beleidsveld/ce6422dc-28ad-4efd-81ca-ea9e258e92f9>)
    (<http://themis.vlaanderen.be/id/beleidsveld/3ada201d-68dd-41a3-b0da-5a8ef27de879> <http://themis.vlaanderen.be/id/beleidsveld/1b6c4206-b591-4a53-a27c-1c125784fc19>)
    (<http://themis.vlaanderen.be/id/beleidsveld/64634310-4c8d-46a3-ac4a-e7777a434729> <http://themis.vlaanderen.be/id/beleidsveld/e9361eb8-9a30-4c0b-8664-3dad70a8666d>)
    (<http://themis.vlaanderen.be/id/beleidsveld/d185e71b-2a6f-49e5-b710-3d9f58ddf11b> <http://themis.vlaanderen.be/id/beleidsveld/342eb9bf-9f60-449a-b932-219e3347bb4f>)
    (<http://themis.vlaanderen.be/id/beleidsveld/a84f868d-de05-4a62-b7eb-fc676479a6d2> <http://themis.vlaanderen.be/id/beleidsveld/9952d392-2a11-4af1-8362-ae1570c17e4a>)
    (<http://themis.vlaanderen.be/id/beleidsveld/624264fe-0e06-48c1-9e97-eeb4089f5971> <http://themis.vlaanderen.be/id/beleidsveld/809fa52e-38c0-4f21-8ec3-5348e0340141>)
    (<http://themis.vlaanderen.be/id/beleidsveld/eddfc369-3b67-45a1-b0a2-d527a03c1ce1> <http://themis.vlaanderen.be/id/beleidsveld/a4469e75-2406-4d45-97ff-523633b5b3ed>)
    (<http://themis.vlaanderen.be/id/beleidsveld/b5eb0138-b286-473e-8f06-5647db7ac120> <http://themis.vlaanderen.be/id/beleidsveld/57002a1f-7c3e-4aa0-82ef-3fdf74e78f27>)
    (<http://themis.vlaanderen.be/id/beleidsveld/d5193292-bdc1-4c7d-ba0a-661219108801> <http://themis.vlaanderen.be/id/beleidsveld/196e9d0e-1e85-492d-8a24-d31ed7d5e887>)
    (<http://themis.vlaanderen.be/id/beleidsveld/59e231ce-97d2-4576-a152-c2807eefa5b6> <http://themis.vlaanderen.be/id/beleidsveld/69775eb0-5497-46a2-b5ba-51b08138233b>)
    (<http://themis.vlaanderen.be/id/beleidsveld/32c9b7d9-6fe5-4e68-bd4f-0f895fadeb4c> <http://themis.vlaanderen.be/id/beleidsveld/6b8b6eb0-1c11-4b26-9c41-276bc739e080>)
    (<http://themis.vlaanderen.be/id/beleidsveld/0db685d1-811f-49f9-a6fe-348aab08bba4> <http://themis.vlaanderen.be/id/beleidsveld/d3991f72-c8d7-4a87-baca-fdaf97a09b2e>)
    (<http://themis.vlaanderen.be/id/beleidsveld/4fbef468-55dd-4191-96bd-e0ac9e28aa91> <http://themis.vlaanderen.be/id/beleidsveld/dc701148-ebb8-420e-89bb-f38527ceb836>)
    (<http://themis.vlaanderen.be/id/beleidsveld/19c1626d-1172-48f9-81d7-368015eb3489> <http://themis.vlaanderen.be/id/beleidsveld/3e4c674c-b707-402f-adfd-ffb0b18f2eaf>)
    (<http://themis.vlaanderen.be/id/beleidsveld/0f693798-541d-49ee-b705-4643661402a2> <http://themis.vlaanderen.be/id/beleidsveld/7cc24d74-6864-49aa-b3cd-dfd5ad83ad84>)
    (<http://themis.vlaanderen.be/id/beleidsveld/2b0103aa-a3e8-4718-80f8-8de405966c57> <http://themis.vlaanderen.be/id/beleidsveld/433230a0-a118-47e4-8f4e-d76ea283922b>)
    (<http://themis.vlaanderen.be/id/beleidsveld/2731fdbe-592b-414c-8675-22a7b9d7b3bc> <http://themis.vlaanderen.be/id/beleidsveld/96ec093f-9541-4029-82b1-02c5ea84de49>)
    (<http://themis.vlaanderen.be/id/beleidsveld/10d5f8a5-3dfe-4661-b6a2-c2ca98f819a3> <http://themis.vlaanderen.be/id/beleidsveld/9d197a40-1390-4132-8378-193c81ce918e>)
    (<http://themis.vlaanderen.be/id/beleidsveld/114e5c23-e495-41b7-995c-bc390b5234a0> <http://themis.vlaanderen.be/id/beleidsveld/3f0cbc25-3702-42d0-8d4e-2eaf4baa1727>)
    (<http://themis.vlaanderen.be/id/beleidsveld/5de93340-ce1a-4886-8425-6c80bbe0351b> <http://themis.vlaanderen.be/id/beleidsveld/4f7a46d0-bf22-4be5-9029-9235e69dbe06>)
    (<http://themis.vlaanderen.be/id/beleidsveld/08249005-75e6-4791-ac7f-dbbb3a4d79c4> <http://themis.vlaanderen.be/id/beleidsveld/4095fd6b-fcff-4890-b0bb-114a452f9b5e>)
    (<http://themis.vlaanderen.be/id/beleidsveld/01f64f4e-d435-4f98-8260-7e1843bf1555> <http://themis.vlaanderen.be/id/beleidsveld/8509d78a-c468-4bfa-9226-cb75782a7864>)
    (<http://themis.vlaanderen.be/id/beleidsveld/43b8de2e-61f9-4cf8-a018-9f3cc27f4103> <http://themis.vlaanderen.be/id/beleidsveld/6493e75f-6cee-409b-ad56-763b9b516ff3>)
    (<http://themis.vlaanderen.be/id/beleidsveld/35d0740c-2754-4ca3-a334-936401383bcf> <http://themis.vlaanderen.be/id/beleidsveld/acd345db-dff2-4a96-9507-df81e5acf92f>)
    (<http://themis.vlaanderen.be/id/beleidsveld/80106fa7-3f9d-4313-b3e1-040bf0e07410> <http://themis.vlaanderen.be/id/beleidsveld/6cafaa19-e4a1-400b-b96d-00789aae02d4>)
    (<http://themis.vlaanderen.be/id/beleidsveld/13842fbc-441c-46ca-a58d-f78a64eb8a93> <http://themis.vlaanderen.be/id/beleidsveld/5b67a681-8a6d-43f4-91c3-bc4add80c670>)
    (<http://themis.vlaanderen.be/id/beleidsveld/da9202a5-c504-4f2c-8865-055cf472b3e4> <http://themis.vlaanderen.be/id/beleidsveld/4267e94e-2600-40d7-a96c-d53c68bcf976>)
    (<http://themis.vlaanderen.be/id/beleidsveld/ff815ebf-7a96-42be-90fc-88824854e6a6> <http://themis.vlaanderen.be/id/beleidsveld/76e7a84a-868a-4a7e-9cfc-7612219e6509>)
    (<http://themis.vlaanderen.be/id/beleidsveld/1a2aa428-d8c4-4fa1-aa1e-1c3851c382b2> <http://themis.vlaanderen.be/id/beleidsveld/8d4e6942-8432-4150-a97f-f47809aeeebe>)
    (<http://themis.vlaanderen.be/id/beleidsveld/52e877e2-d342-4b0c-9835-74368a296d6c> <http://themis.vlaanderen.be/id/beleidsveld/cf35538f-203c-4c95-849c-d1c2794207a1>)
    (<http://themis.vlaanderen.be/id/beleidsveld/e4d93deb-7e21-4838-b83d-da6b8c562723> <http://themis.vlaanderen.be/id/beleidsveld/7d420139-0479-4062-9ee2-d44299326105>)
    (<http://themis.vlaanderen.be/id/beleidsveld/c08ccb06-460f-4bb7-87d5-714a94c5186b> <http://themis.vlaanderen.be/id/beleidsveld/18a67a9c-d79c-4420-ba82-591773b64524>)
    (<http://themis.vlaanderen.be/id/beleidsveld/c48135d7-f235-460a-af3b-deb3954e6a32> <http://themis.vlaanderen.be/id/beleidsveld/cb9a10be-77f6-4e9e-91f7-98ee76e90d07>)
    (<http://themis.vlaanderen.be/id/beleidsveld/8f23ea03-637f-4d4b-8135-7281a6358ab1> <http://themis.vlaanderen.be/id/beleidsveld/217e0c03-7081-4733-91e4-0e31784035d1>)
    (<http://themis.vlaanderen.be/id/beleidsveld/fc405ce9-5535-440d-a121-5deacab67d28> <http://themis.vlaanderen.be/id/beleidsveld/8e0e8842-68a6-4def-a074-45f8f64dc117>)
    (<http://themis.vlaanderen.be/id/beleidsveld/d83bfbfd-5821-4cf3-85cc-c7201f9343a6> <http://themis.vlaanderen.be/id/beleidsveld/372427bf-e507-48ee-8e9e-3ba30ae83330>)
    (<http://themis.vlaanderen.be/id/beleidsveld/72b6fc10-b729-40f3-9c03-9f7d55e076a7> <http://themis.vlaanderen.be/id/beleidsveld/5ef43b73-bc13-479e-b470-e415307798cd>)
    (<http://themis.vlaanderen.be/id/beleidsveld/82208ea2-8371-4ed1-906f-5ae4c101caee> <http://themis.vlaanderen.be/id/beleidsveld/3449d2b8-f064-4d44-92ac-349baf27fbd6>)
    (<http://themis.vlaanderen.be/id/beleidsveld/4cd5d9d1-099b-437e-be1a-99c069469fcb> <http://themis.vlaanderen.be/id/beleidsveld/0f1085c5-5d8c-4da5-bc0c-aaeb64555042>)
    (<http://themis.vlaanderen.be/id/beleidsveld/ea4c45da-a07d-49c9-92ab-16d0a0d4e37e> <http://themis.vlaanderen.be/id/beleidsveld/0a86df18-bf47-403b-aa35-98c938679482>)
    (<http://themis.vlaanderen.be/id/beleidsveld/d1b93810-6066-4b0e-ad31-130c7ae838ac> <http://themis.vlaanderen.be/id/beleidsveld/7ea8b04e-f2e4-4620-868d-e8b41f946282>)
    (<http://themis.vlaanderen.be/id/beleidsveld/998b165e-3c6d-4722-bd1f-af3de421628e> <http://themis.vlaanderen.be/id/beleidsveld/b3bc1a8a-8b40-423f-8069-7cf350c05444>)
    (<http://themis.vlaanderen.be/id/beleidsveld/b2cdd186-bced-41af-9533-7e234996f16e> <http://themis.vlaanderen.be/id/beleidsveld/88320309-6576-4033-979d-0d3ea057d28c>)
    (<http://themis.vlaanderen.be/id/beleidsveld/cd9b9d89-5757-448d-a887-10acfc67adfb> <http://themis.vlaanderen.be/id/beleidsveld/e8723667-560c-4449-8a2e-5e4d1a661a8b>)
    (<http://themis.vlaanderen.be/id/beleidsveld/148a2622-b159-4bf7-b6f2-0ec8a5ce2194> <http://themis.vlaanderen.be/id/beleidsveld/dd9b883e-2223-4416-b83f-f2bd2f8b791a>)
  }
}