; (define-resource mailbox ()
;   :class (s-prefix "nmo:Mailbox")
;   :properties `((:id :string ,(s-prefix "nie:identifier")))
;   :has-many `((folder :via ,(s-prefix "nie:hasPart")
;                     :as "folders"))
;   :resource-base (s-url "http://themis.vlaanderen.be/id/mailbox/")
;   :features '(include-uri)
;   :on-path "mailboxes")

(define-resource folder ()
  :class (s-prefix "nfo:Folder")
  :properties `((:name :string ,(s-prefix "nie:title"))
                (:description :string ,(s-prefix "nie:description")))
  :has-many `((email :via ,(s-prefix "nmo:isPartOf") ;; TODO: nie:isPartOf isn't valid part of NEPOMUK
                    :inverse t
                    :as "emails")
             (folder :via ,(s-prefix "email:hasFolder");;hack, as mu-cl-resources doesn't support superclasses yet (http://oscaf.sourceforge.net/nmo.html#nmo:MailboxDataObject)
                    :as "folders"))
  :resource-base (s-url "http://themis.vlaanderen.be/id/mail-folder/")
  :features '(include-uri)
  :on-path "mail-folders")

(define-resource email ()
  :class (s-prefix "nmo:Email")
  :properties `((:message-id :string ,(s-prefix "nmo:messageId"));; e-mail protocol-specific id: https://tools.ietf.org/html/rfc2822#section-3.6.4
                (:from :string ,(s-prefix "nmo:messageFrom"))
                (:to :string ,(s-prefix "nmo:emailTo"))
                (:cc :string ,(s-prefix "nmo:emailCc"))
                (:bcc :string ,(s-prefix "nmo:emailBcc"))
                (:reply-to :string ,(s-prefix "nmo:messageReplyTo"))
                (:subject :string ,(s-prefix "nmo:messageSubject"))
                (:message :string ,(s-prefix "nmo:plainTextMessageContent"))
                (:html-content :string ,(s-prefix "nmo:htmlMessageContent"))
                (:is-read :boolean ,(s-prefix "nmo:isRead"))
                (:content-mime-type :string ,(s-prefix "nmo:contentMimeType"))
                (:received-date :datetime ,(s-prefix "nmo:receivedDate"))
                (:sent-date :datetime ,(s-prefix "nmo:sentDate")))
  :has-one `((email :via ,(s-prefix "nmo:inReplyTo")
                    :as "in-reply-to")
             (folder :via ,(s-prefix "nmo:isPartOf") ;; TODO: nie:isPartOf isn't valid part of NEPOMUK
                    :as "folder")
             (request-activity :via ,(s-prefix "pub:requestActivitySubject") ;; FIXME: predicate should be "dct:subject"
                               :as "request-activity"))
  :has-many `(
  ;           (email-header :via ,(s-prefix "nmo:messageHeader")
  ;                 :as "headers")
              (file :via ,(s-prefix "nmo:hasAttachment")
                    :as "attachments"))
  ;           (email :via ,(s-prefix "nmo:references");;https://tools.ietf.org/html/rfc2822#section-3.6.4
  ;                   :as "references"))
  :resource-base (s-url "http://themis.vlaanderen.be/id/email/")
  :features '(include-uri)
  :on-path "emails")

(define-resource email-notification-setting ()
  :class (s-prefix "ext:EmailNotificationSettings")
  :properties `((:default-from-email :string ,(s-prefix "ext:defaultFromEmail"))
                (:translation-request-to-email :string ,(s-prefix "ext:translationRequestToEmail"))
                (:translation-request-cc-email :string ,(s-prefix "ext:translationRequestCcEmail"))
                (:translation-request-reply-to-email :string ,(s-prefix "ext:translationRequestReplyToEmail"))
                (:proof-request-to-email :string ,(s-prefix "ext:proofRequestToEmail"))
                (:proof-request-cc-email :string ,(s-prefix "ext:proofRequestCcEmail"))
                (:proof-request-reply-to-email :string ,(s-prefix "ext:proofRequestReplyToEmail"))
                (:publication-request-to-email :string ,(s-prefix "ext:publicationRequestToEmail"))
                (:publication-request-cc-email :string ,(s-prefix "ext:publicationRequestCcEmail"))
                (:publication-request-reply-to-email :string ,(s-prefix "ext:publicationRequestReplyToEmail"))
              )
  :resource-base (s-url "http://themis.vlaanderen.be/id/email-notificatie-settings/")
  :features '(include-uri)
  :on-path "email-notification-settings")

; (define-resource email-header ()
;   :class (s-prefix "nmo:MessageHeader")
;   :properties `((:header-name :string ,(s-prefix "nmo:headerName"))
;                 (:header-value :string ,(s-prefix "nmo:headerValue")))
;   :has-one `((email :via ,(s-prefix "nmo:messageHeader")
;                          :inverse t
;                          :as "email"))
;   :resource-base (s-url "http://themis.vlaanderen.be/id/email-header/")
;   :features '(include-uri)
;   :on-path "email-headers")
