(define-resource document-state ()
  :class (s-prefix "ext:DocumentStatus")
  :properties `((:label :string ,(s-prefix "skos:prefLabel"))
                (:alt-label :string ,(s-prefix "skos:altLabel")))
  :resource-base (s-url "http://kanselarij.vo.data.gift/id/concept/document-statussen/")
  :features `(no-pagination-defaults include-uri)
  :on-path "document-states")

(define-resource file ()
  :class (s-prefix "nfo:FileDataObject")
  :properties `((:filename      :string ,(s-prefix "nfo:fileName"))
                (:format        :string ,(s-prefix "dct:format"))
                (:size          :number ,(s-prefix "nfo:fileSize"))
                (:extension     :string ,(s-prefix "dbpedia:fileExtension"))
                (:created       :datetime ,(s-prefix "nfo:fileCreated"))
                (:content-type  :string ,(s-prefix "ext:contentType")))
  :has-one `((file              :via ,(s-prefix "nie:dataSource")
                                :inverse t
                                :as "download")
             (agenda            :via ,(s-prefix "ext:getekendeNotule")
                                :inverse t
                                :as "agenda"))
  :resource-base (s-url "http://kanselarij.vo.data.gift/id/files/")
  :features `(no-pagination-defaults include-uri)
  :on-path "files")
