(define-resource file ()
  :class (s-prefix "nfo:FileDataObject")
  :properties `((:filename      :string     ,(s-prefix "nfo:fileName"))
                (:format        :string     ,(s-prefix "dct:format"))
                (:size          :integer    ,(s-prefix "nfo:fileSize"))
                (:extension     :string     ,(s-prefix "dbpedia:fileExtension"))
                (:created       :datetime   ,(s-prefix "dct:created")))
  :has-one `((file              :via        ,(s-prefix "nie:dataSource")
                                :inverse t
                                :as "download")
             (file              :via        ,(s-prefix "prov:hadPrimarySource")
                                :as "source")
             (file              :via        ,(s-prefix "prov:hadPrimarySource")
                                :inverse t
                                :as "derived"))
  :resource-base (s-url "http://themis.vlaanderen.be/id/bestand/")
  :features `(no-pagination-defaults include-uri)
  :on-path "files")
