(define-resource oc-meeting ()
  :class (s-prefix "oc:Meeting")
  :properties `((:started-at            :datetime ,(s-prefix "prov:startedAtTime"))
                (:extra-info            :string   ,(s-prefix "ext:extraInfo")))
  :has-many `((oc-agendaitem            :via      ,(s-prefix "oc:agendaItem")
                                        :as "agenda-items"))
                                        
  :resource-base (s-url "http://kanselarij.vo.data.gift/id/oc-zittingen/")
  :features '(include-uri)
  :on-path "oc-meetings")

(define-resource oc-agendaitem ()
  :class (s-prefix "oc:AgendaItem")
  :properties `((:priority            :number   ,(s-prefix "oc:priority"))
                (:sub-priority        :string   ,(s-prefix "oc:subPriority"))
                (:subject             :string   ,(s-prefix "dct:subject"))
                (:distribution-date   :date     ,(s-prefix "oc:distributionDate")))
  :has-one `((oc-case                 :via      ,(s-prefix "oc:caseAgendaItem")
                                      :inverse t
                                      :as "case")
             (oc-meeting              :via      ,(s-prefix "oc:agendaItem")
                                      :inverse t
                                      :as "meeting")
             (file                    :via      ,(s-prefix "oc:meetingRecord")
                                      :as "meeting-record")
             (file                    :via     ,(s-prefix "oc:notification")
                                      :as "notification"))
  :has-many `((government-body        :via      ,(s-prefix "oc:submitter")
                                      :as "submitters")
              (file                   :via     ,(s-prefix "oc:files")
                                      :as "documents"))
  :resource-base (s-url "http://kanselarij.vo.data.gift/id/oc-agendapunten/")
  :features `(include-uri)
  :on-path "oc-agendaitems")

(define-resource oc-case ()
  :class (s-prefix "oc:Case")
  :properties `((:identifier          :string   ,(s-prefix "dct:identifier")))
  :has-many `((oc-agendaitem          :via      ,(s-prefix "oc:caseAgendaItem")
                                      :as "agenda-items"))
  :resource-base (s-url "http://kanselarij.vo.data.gift/id/oc-dossiers/")
  :features `(include-uri)
  :on-path "oc-cases")
