(define-resource organization ()
  :class (s-prefix "org:Organization")
  :properties `((:name :string ,(s-prefix "skos:prefLabel")))
  :has-one `((site :via ,(s-prefix "org:hasPrimarySite")
                   :as "site")
             )
  :has-many `((contact-point :via ,(s-prefix "schema:contactPoint")
                             :as "contact-points")
              (post :via ,(s-prefix "org:hasPost")
                    :as "posts"))
  :resource-base (s-url "http://kanselarij.vo.data.gift/id/organisaties/")
  :features '(include-uri)
  :on-path "organizations"
)

